package com.waypoint.planning.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.waypoint.planning.entity.*;import com.waypoint.planning.exception.PlanningException;import com.waypoint.planning.jpa.*;import com.waypoint.planning.messaging.PlanningEventPublisher;import com.waypoint.planning.model.PlanningModels.*;import com.waypoint.planning.port.PlanningMasterDataPort;import org.junit.jupiter.api.*;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class DeferralServiceJpaTest {
 private PlanningMasterDataPort master;private AllocationJpaRepository allocations;private DeferralRecordJpaRepository records;private PlanningDecisionJpaRepository decisions;private PlanningEventPublisher events;private DeferralService service;private UUID orderId;private OrderRef order;
 @BeforeEach void setup(){master=mock(PlanningMasterDataPort.class);allocations=mock(AllocationJpaRepository.class);records=mock(DeferralRecordJpaRepository.class);decisions=mock(PlanningDecisionJpaRepository.class);events=mock(PlanningEventPublisher.class);service=new DeferralService(master,allocations,records,decisions,events,new ObjectMapper().findAndRegisterModules());orderId=UUID.randomUUID();order=new OrderRef(orderId,"OUT","Outlet","District","DEPOT","STANDARD",null,null,"SKU",1,10,1,"Fresh","AMBIENT",LocalDate.now(),LocalTime.MIN,LocalTime.MAX,"PENDING");when(master.getOrder(orderId)).thenReturn(order);when(records.save(any())).thenAnswer(i->{DeferralRecordEntity r=i.getArgument(0);ReflectionTestUtils.setField(r,"id",UUID.randomUUID());return r;});}
 @Test void deferPersistsAllocationRecordDecisionAndAfterCommitPublisher(){UUID id=service.defer(orderId,new DeferralRequest("capacity","CAPACITY","capacity","VOLUME",null,LocalDate.now().plusDays(1),"note"),"dispatcher");assertThat(id).isNotNull();verify(allocations).save(argThat(a->a.getStatus()==AllocationStatus.DEFERRED));verify(records).save(any());verify(decisions).save(argThat(d->"ORDER_DEFERRED".equals(d.getType())));verify(events).orderDeferred(eq(orderId),eq("capacity"),eq("VOLUME"),eq(LocalDate.now().plusDays(1)));}
 @Test void changeDateKeepsDeferredAndWritesAudit(){AllocationEntity allocation=AllocationEntity.deferred(orderId,"reason",LocalDate.now().plusDays(1),"user");DeferralRecordEntity record=new DeferralRecordEntity(orderId,LocalDate.now(),"reason","NONE",LocalDate.now().plusDays(1),null);when(allocations.findFirstByOrderIdAndStatusOrderByIdDesc(orderId,AllocationStatus.DEFERRED)).thenReturn(Optional.of(allocation));when(records.findFirstByOrderIdAndStatusOrderByCreatedAtDesc(orderId,"ACTIVE")).thenReturn(Optional.of(record));LocalDate changed=LocalDate.now().plusDays(2);service.updateNextDate(orderId,new UpdateNextPlannedDateRequest(changed,"reschedule"));assertThat(allocation.getStatus()).isEqualTo(AllocationStatus.DEFERRED);assertThat(allocation.getRetryDate()).isEqualTo(changed);assertThat(record.getNextPlannedDate()).isEqualTo(changed);verify(decisions).save(argThat(d->"DEFERRAL_DATE_CHANGED".equals(d.getType())));}
 @Test void returnPreservesHistoryAndMarksState(){AllocationEntity allocation=AllocationEntity.deferred(orderId,"reason",LocalDate.now().plusDays(1),"user");DeferralRecordEntity record=new DeferralRecordEntity(orderId,LocalDate.now(),"reason","NONE",LocalDate.now().plusDays(1),null);when(allocations.findFirstByOrderIdAndStatusOrderByIdDesc(orderId,AllocationStatus.DEFERRED)).thenReturn(Optional.of(allocation));when(records.findFirstByOrderIdAndStatusOrderByCreatedAtDesc(orderId,"ACTIVE")).thenReturn(Optional.of(record));service.returnToPlanning(orderId);assertThat(allocation.getStatus()).isEqualTo(AllocationStatus.RETURNED_TO_PLANNING);assertThat(record.getStatus()).isEqualTo("RETURNED_TO_PLANNING");verify(records,never()).delete(any());verify(decisions).save(argThat(d->"RETURNED_TO_PLANNING".equals(d.getType())));}
 @Test void failedDeferralPublishesNoEvent(){when(allocations.findFirstByOrderIdAndStatusOrderByIdDesc(orderId,AllocationStatus.DEFERRED)).thenReturn(Optional.of(AllocationEntity.deferred(orderId,"old",LocalDate.now().plusDays(1),"user")));assertThatThrownBy(()->service.defer(orderId,new DeferralRequest("again",null,null,"NONE",null,LocalDate.now().plusDays(2),null),"user")).isInstanceOf(PlanningException.class);verifyNoInteractions(events);}
}
