package com.waypoint.planning.integration;

import com.fasterxml.jackson.databind.*;import com.waypoint.planning.messaging.PlanningEventPublisher;import jakarta.persistence.EntityManager;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.core.io.FileSystemResource;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.init.ScriptUtils;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
import java.sql.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@Testcontainers(disabledWithoutDocker=true)
@SpringBootTest(properties={"grpc.server.port=-1","waypoint.planning.master-data.mode=jdbc"})
@AutoConfigureMockMvc
class PlanningPostgresIntegrationTest {
 @Container static final PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16-alpine").withDatabaseName("waypoint").withUsername("waypoint").withPassword("waypoint");
 @DynamicPropertySource static void database(DynamicPropertyRegistry registry)throws Exception{postgres.start();try(Connection connection=DriverManager.getConnection(postgres.getJdbcUrl(),postgres.getUsername(),postgres.getPassword())){try(Statement statement=connection.createStatement()){statement.execute("CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY, email text, raw_user_meta_data jsonb DEFAULT '{}'::jsonb); CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql IMMUTABLE AS 'SELECT ''service_role''::text'; CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULL::uuid'");}ScriptUtils.executeSqlScript(connection,new FileSystemResource("../../supabase/migrations/20260927000001_auth_schema.sql"));ScriptUtils.executeSqlScript(connection,new FileSystemResource("../../supabase/migrations/20260927000002_order_schema.sql"));ScriptUtils.executeSqlScript(connection,new FileSystemResource("../../supabase/migrations/20260927000003_planning_schema.sql"));}registry.add("spring.datasource.url",postgres::getJdbcUrl);registry.add("spring.datasource.username",postgres::getUsername);registry.add("spring.datasource.password",postgres::getPassword);registry.add("spring.rabbitmq.host",()->"127.0.0.1");registry.add("spring.rabbitmq.password",()->"unused");}
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;@Autowired EntityManager entityManager;@MockBean PlanningEventPublisher events;
 private UUID orderA;private UUID orderB;
 @BeforeEach void seed(){jdbc.update("INSERT INTO public.outlets(outlet_id,name,district,depot,parking_type) VALUES ('OUT-I','Integration Outlet','Colombo','D1','STANDARD') ON CONFLICT DO NOTHING");jdbc.update("INSERT INTO public.vehicles(vehicle_id,registration,type,weight_cap_kg,volume_cap_m3,temp_capability,depot,brand,is_active) VALUES ('VEH-I','INT-001','TRUCK',4000,18,'CHILLED','D1','Fresh',true) ON CONFLICT DO NOTHING");jdbc.update("INSERT INTO public.vehicle_planning_state(vehicle_id,available,weekly_fuel_quota_l,weekly_fuel_used_l) VALUES ('VEH-I',true,100,20) ON CONFLICT(vehicle_id) DO UPDATE SET available=true");orderA=insertOrder(820,7.8);orderB=insertOrder(690,6.4);}
 @Test void completeRestWorkflowPersistsAndReloads()throws Exception{String created=mvc.perform(post("/api/planning/trips").contentType("application/json").content("{\"planningDate\":\""+LocalDate.now()+"\",\"homeDepot\":\"D1\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();UUID trip=UUID.fromString(json.readTree(created).get("tripId").asText());add(trip,orderA);add(trip,orderB);mvc.perform(put("/api/planning/trips/{id}/vehicle",trip).contentType("application/json").content("{\"vehicleId\":\"VEH-I\"}")).andExpect(status().isOk());mvc.perform(put("/api/planning/trips/{id}/stops",trip).contentType("application/json").content(json.writeValueAsString(Map.of("orderIds",List.of(orderB,orderA))))).andExpect(status().isOk());mvc.perform(post("/api/planning/trips/{id}/validate",trip)).andExpect(status().isOk()).andExpect(jsonPath("$.feasible").value(true)).andExpect(jsonPath("$.totalWeight").value(1510.0));mvc.perform(post("/api/planning/trips/{id}/confirm",trip).header("X-User-Id","integration-dispatcher")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CONFIRMED"));entityManager.clear();mvc.perform(get("/api/planning/trips/{id}",trip)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CONFIRMED")).andExpect(jsonPath("$.vehicleId").value("VEH-I")).andExpect(jsonPath("$.stops[0].orderId").value(orderB.toString()));assertThat(jdbc.queryForObject("SELECT count(*) FROM public.allocations WHERE trip_id=? AND status::text='ALLOCATED'",Integer.class,trip)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT count(*) FROM public.trip_stops WHERE trip_id=?",Integer.class,trip)).isEqualTo(2);verify(events,times(1)).allocationCompleted(eq(trip),eq("VEH-I"),anyList(),eq(LocalDate.now()));mvc.perform(post("/api/planning/trips/{id}/confirm",trip)).andExpect(status().isConflict());mvc.perform(delete("/api/planning/trips/{id}/orders/{orderId}",trip,orderA)).andExpect(status().isConflict());}
 private void add(UUID trip,UUID order)throws Exception{mvc.perform(post("/api/planning/trips/{id}/orders",trip).contentType("application/json").content("{\"orderId\":\""+order+"\"}")).andExpect(status().isOk());}
 private UUID insertOrder(double weight,double volume){return jdbc.queryForObject("INSERT INTO public.orders(outlet_id,product_code,quantity,weight_kg,volume_m3,brand,temp_requirement,preferred_date,window_open,window_close,status) VALUES ('OUT-I','SKU',1,?,?, 'Fresh','CHILLED',?, '06:00','12:00','PENDING') RETURNING order_id",UUID.class,weight,volume,LocalDate.now());}
}
