package com.waypoint.order.repository;
import com.fasterxml.jackson.databind.ObjectMapper;import com.waypoint.order.dto.OrderModels.*;import com.waypoint.order.exception.ApiException;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;import java.sql.*;import java.time.*;import java.util.*;
@Repository public class OrderRepository {
 private final JdbcTemplate jdbc;private final ObjectMapper json;public OrderRepository(JdbcTemplate j,ObjectMapper o){jdbc=j;json=o;}
 public String outletFor(UUID user){return jdbc.query("SELECT outlet_id FROM public.user_profiles WHERE id=?",r->r.next()?r.getString(1):null,user);}
 public Map<String,Object> outlet(String id){return jdbc.queryForMap("SELECT outlet_id,name,district,depot,parking_type::text,COALESCE(brand,'') brand,address,contact_name,contact_phone FROM public.outlets WHERE outlet_id=?",id);}
 public List<Map<String,Object>> outlets(){return jdbc.queryForList("SELECT outlet_id,name,district,depot,parking_type::text,COALESCE(brand,'') brand,address,contact_name,contact_phone FROM public.outlets WHERE is_active ORDER BY name");}
 public List<Map<String,Object>> vehicles(){return jdbc.queryForList("SELECT vehicle_id,registration,type::text,weight_cap_kg,volume_cap_m3,temp_capability::text,depot,brand,in_workshop FROM public.vehicles WHERE is_active ORDER BY vehicle_id");}
 @Transactional public UUID place(String outlet,UUID user,PlaceOrderRequest req,Instant now){
  var ref=outlet(outlet);String brand=Objects.toString(ref.get("brand"));if(brand.isBlank())throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"OUTLET_BRAND_MISSING","Outlet reference data has no brand");
  var temps=req.items().stream().map(x->x.tempRequirement().toUpperCase()).distinct().toList();if(temps.size()!=1)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"MIXED_TEMPERATURE","Place ambient and chilled items as separate orders");
  BigDecimal weight=req.items().stream().map(x->x.weightKg().multiply(BigDecimal.valueOf(x.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);
  BigDecimal volume=req.items().stream().map(x->x.volumeM3().multiply(BigDecimal.valueOf(x.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);
  int qty=req.items().stream().mapToInt(ItemRequest::quantity).sum();BigDecimal value=req.items().stream().map(x->x.unitPrice().multiply(BigDecimal.valueOf(x.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);
  UUID id=UUID.randomUUID();String product=req.items().size()==1?req.items().getFirst().productCode():"MULTI";LocalTime open=brand.equalsIgnoreCase("Fresh")?LocalTime.of(6,0):LocalTime.of(8,0);LocalTime close=brand.equalsIgnoreCase("Fresh")?LocalTime.of(8,0):LocalTime.of(17,0);
  jdbc.update("INSERT INTO public.orders(order_id,outlet_id,product_code,quantity,weight_kg,volume_m3,brand,temp_requirement,preferred_date,window_open,window_close,status,placed_by,notes,lifecycle_status,confirmed_at,closed_at,order_value) VALUES(?,?,?,?,?,?,?,?::public.temp_requirement,?,?,?,'PENDING',?,?, 'CONFIRMED',?,?,?)",id,outlet,product,qty,weight,volume,brand,temps.getFirst(),req.requestedDeliveryDate(),open,close,user,req.notes(),Timestamp.from(now),Timestamp.from(now),value);
  for(var i:req.items())jdbc.update("INSERT INTO public.order_items(order_id,product_code,quantity,weight_kg,volume_m3,temp_requirement,unit_price) VALUES(?,?,?,?,?,?::public.temp_requirement,?)",id,i.productCode(),i.quantity(),i.weightKg(),i.volumeM3(),i.tempRequirement().toUpperCase(),i.unitPrice());
  timeline(id,"PLACED","Order placed",now);timeline(id,"CONFIRMED","Order confirmed",now);outbox("ORDER_PLACED","order.placed",id,Map.of("order_id",id,"outlet_id",outlet,"requested_delivery_date",req.requestedDeliveryDate(),"status","CONFIRMED","items",req.items()));return id;
 }
 public List<OrderView> list(String outlet,String status){String sql="SELECT order_id FROM public.orders WHERE (? IS NULL OR outlet_id=?) AND (? IS NULL OR lifecycle_status=?) ORDER BY created_at DESC";return jdbc.query(sql,(r,n)->view(r.getObject(1,UUID.class)),outlet,outlet,status,status);}
 public OrderView view(UUID id){var rows=jdbc.query("SELECT order_id,outlet_id,lifecycle_status,preferred_date,expected_arrival,deferral_reason FROM public.orders WHERE order_id=?",(r,n)->new Object[]{r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getObject(4,LocalDate.class),ts(r,5),r.getString(6)},id);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Order not found");var x=rows.getFirst();return new OrderView((UUID)x[0],(String)x[1],(String)x[2],(LocalDate)x[3],(Instant)x[4],(String)x[5],jdbc.queryForList("SELECT product_code,quantity,weight_kg,volume_m3,temp_requirement::text,unit_price FROM public.order_items WHERE order_id=? ORDER BY product_code",id),jdbc.query("SELECT status,detail,occurred_at FROM public.order_timeline WHERE order_id=? ORDER BY occurred_at,id",(r,n)->new TimelineEntry(r.getString(1),r.getString(2),r.getTimestamp(3).toInstant()),id));}
 private Instant ts(ResultSet r,int n)throws SQLException{var x=r.getTimestamp(n);return x==null?null:x.toInstant();}
 public void ensureOwned(UUID id,String outlet){Integer n=jdbc.queryForObject("SELECT count(*) FROM public.orders WHERE order_id=? AND outlet_id=?",Integer.class,id,outlet);if(n==0)throw new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Order not found");}
 @Transactional public void transition(UUID id,String lifecycle,Instant eta,String reason,String detail){jdbc.update("UPDATE public.orders SET lifecycle_status=?,expected_arrival=COALESCE(?,expected_arrival),deferral_reason=COALESCE(?,deferral_reason),status=CASE WHEN ?='DEFERRED' THEN 'DEFERRED'::public.order_status WHEN ?='DELIVERED' THEN 'DELIVERED'::public.order_status WHEN ?='PLANNED' THEN 'ALLOCATED'::public.order_status ELSE status END WHERE order_id=?",lifecycle,eta==null?null:Timestamp.from(eta),reason,lifecycle,lifecycle,lifecycle,id);timeline(id,lifecycle,detail,Instant.now());}
 private void timeline(UUID id,String status,String detail,Instant at){jdbc.update("INSERT INTO public.order_timeline(order_id,status,detail,occurred_at) VALUES(?,?,?,?) ON CONFLICT(order_id,status) DO UPDATE SET detail=EXCLUDED.detail,occurred_at=EXCLUDED.occurred_at",id,status,detail,Timestamp.from(at));}
 @Transactional public UUID receipt(UUID id,UUID user,ReceiptRequest r){try{String s=json.writeValueAsString(r.lines());jdbc.update("INSERT INTO public.order_receipts(order_id,confirmed_by,lines) VALUES(?,?,?::jsonb)",id,user,s);outbox("ORDER_RECEIPT_CONFIRMED","order.receipt.confirmed",id,Map.of("order_id",id,"confirmed_by",user,"lines",r.lines()));return id;}catch(Exception e){throw new ApiException(HttpStatus.CONFLICT,"RECEIPT_EXISTS","Receipt already confirmed");}}
 @Transactional public UUID issue(UUID id,UUID user,IssueRequest r){UUID issue=UUID.randomUUID();jdbc.update("INSERT INTO public.order_issues(id,order_id,raised_by,issue_type,product_code,quantity,description,photo_url) VALUES(?,?,?,?,?,?,?,?)",issue,id,user,r.type(),r.productCode(),r.quantity(),r.description(),r.photoUrl());outbox("FLAG_RAISED","flag.raised",issue,Map.of("flag_id",issue,"order_id",id,"source","STORE_MANAGER","type",r.type(),"description",Objects.toString(r.description(),""),"photo_url",Objects.toString(r.photoUrl(),"")));return issue;}
 private void outbox(String type,String key,Object aggregate,Object payload){try{jdbc.update("INSERT INTO public.order_outbox(event_type,routing_key,aggregate_id,payload) VALUES(?,?,?,?::jsonb)",type,key,aggregate.toString(),json.writeValueAsString(payload));}catch(Exception e){throw new IllegalStateException(e);}}
}
