package com.waypoint.order.service;
import com.fasterxml.jackson.databind.*;import com.rabbitmq.client.Channel;import com.waypoint.order.repository.OrderRepository;import org.springframework.amqp.core.Message;import org.springframework.amqp.rabbit.annotation.RabbitListener;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;
@Component public class OrderEventConsumer {private final ObjectMapper json;private final JdbcTemplate jdbc;private final OrderRepository repo;public OrderEventConsumer(ObjectMapper j,JdbcTemplate d,OrderRepository r){json=j;jdbc=d;repo=r;}
 @RabbitListener(queues="order.lifecycle") public void receive(Message message,Channel channel)throws Exception{long tag=message.getMessageProperties().getDeliveryTag();try{String key=message.getMessageProperties().getReceivedRoutingKey();process(key,message.getBody());channel.basicAck(tag,false);}catch(Exception e){channel.basicNack(tag,false,false);}}
 @Transactional public void process(String key,byte[] body)throws Exception{String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest((key+new String(body,StandardCharsets.UTF_8)).getBytes(StandardCharsets.UTF_8)));if(jdbc.update("INSERT INTO public.order_event_inbox(event_key,event_type) VALUES(?,?) ON CONFLICT DO NOTHING",hash,key)==0)return;JsonNode root=json.readTree(body);switch(key){case"allocation.completed"->allocation(root);case"order.deferred"->deferred(root);case"loading.completed"->byTrip(root,"LOADED");case"delivery.completed"->delivery(root);default->{}}}
 private void allocation(JsonNode root){for(JsonNode trip:root.path("trips"))for(JsonNode stop:trip.path("stops")){Instant eta=parseEta(root.path("date").asText(),stop.path("eta").asText(null));for(JsonNode order:stop.path("orders")){UUID id=UUID.fromString(order.path("order_id").asText());repo.transition(id,"PLANNED",eta,null,"Allocated to trip "+trip.path("trip_id").asText());}}}
 private Instant parseEta(String date,String time){if(time==null||time.isBlank())return null;return ZonedDateTime.of(LocalDate.parse(date),LocalTime.parse(time),ZoneId.of("Asia/Colombo")).toInstant();}
 private void deferred(JsonNode n){repo.transition(UUID.fromString(n.path("order_id").asText()),"DEFERRED",null,n.path("reason").asText(),"Deferred: "+n.path("reason").asText());}
 private void byTrip(JsonNode n,String status){UUID trip=UUID.fromString(n.path("trip_id").asText());for(UUID id:jdbc.query("SELECT order_id FROM public.allocations WHERE trip_id=?",(r,x)->r.getObject(1,UUID.class),trip))repo.transition(id,status,null,null,status.replace('_',' '));}
 private void delivery(JsonNode n){if(n.hasNonNull("order_id"))repo.transition(UUID.fromString(n.path("order_id").asText()),"DELIVERED",null,null,"Delivery completed");else if(n.hasNonNull("trip_id"))byTrip(n,"DELIVERED");else for(JsonNode id:n.path("order_ids"))repo.transition(UUID.fromString(id.asText()),"DELIVERED",null,null,"Delivery completed");}
}
