// ============================================================
// liveTrackingApi.ts — Mock data and API for Live Tracking
// ============================================================

import type { ActiveTrip, LiveTrackingSummary } from '@/entities/tracking/trackingTypes';
import { apiRequest } from '@/shared/api/apiClient';

/* Legacy fixture retained only as commented history; runtime data is API-only.
const removedTrackingSummary: LiveTrackingSummary = {
  activeTripsCount: 8,
  onTimeCount: 6,
  atRiskCount: 1,
  issuesCount: 1,
  lastUpdated: '10:18',
};

const removedActiveTrips: ActiveTrip[] = [
  {
    id: 'TRIP-0925-014',
    tripCode: 'TRIP-0925-014',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH014',
    vehicleType: 'Reefer',
    vehicleFullName: 'Refrigerated Truck',
    vehiclePlate: 'WP - CAB - 4421',
    driverName: 'Dilan Fernando',
    driverInitials: 'DF',
    driverStatus: 'Active · On route',
    origin: 'Peliyagoda',
    destination: 'Colombo',
    fullRouteText: 'Peliyagoda Depot → Colombo District',
    completedStops: 4,
    totalStops: 6,
    eta: '10:40',
    delayText: '+12 min',
    nextStopName: 'Colombo 07',
    nextStopFullName: 'Waypoint Fresh — Colombo 07',
    nextStopEta: '10:40',
    nextStopWindow: '10:00 - 10:30',
    nextStopOrder: 'ORD-0925-014',
    nextStopTemperature: 'Chilled',
    nextStopItemsText: '12 chilled items',
    weightKg: 3360,
    maxWeightKg: 4000,
    volumeM3: 15.4,
    maxVolumeM3: 18.0,
    chilledItemsCount: 12,
    totalOrdersCount: 6,
    temperatureStatus: 'Within range',
    homeDepot: 'Peliyagoda',
    tripUsage: 'Trip 1 of 2',
    todayTrips: '1/2',
    tripLoadedTime: '07:50',
    tripDepartedTime: '08:10',
    stops: [
      {
        id: 'stop-1',
        stopNumber: 1,
        name: 'Peliyagoda Depot',
        status: 'DEPOT',
        timeText: 'Departed - 08:10',
        locationArea: 'Peliyagoda',
        mapCoords: { x: 22, y: 39 },
      },
      {
        id: 'stop-2',
        stopNumber: 2,
        name: 'Waypoint Style — Wattala',
        orderId: 'ORD-0925-011',
        status: 'DELIVERED',
        timeText: 'Delivered 09:05',
        locationArea: 'Wattala',
        mapCoords: { x: 35, y: 39 },
      },
      {
        id: 'stop-3',
        stopNumber: 3,
        name: 'Waypoint Tech — Bambalapitiya',
        orderId: 'ORD-0925-022',
        status: 'DELIVERED',
        timeText: 'Delivered 09:38',
        locationArea: 'Colombo 03',
        mapCoords: { x: 48, y: 52 },
      },
      {
        id: 'stop-4',
        stopNumber: 4,
        name: 'Waypoint Fresh — Colombo 07',
        orderId: 'ORD-0925-014',
        status: 'NEXT',
        timeText: 'ETA 10:40',
        deliveryWindow: '10:00 - 10:30',
        itemsText: '12 chilled items',
        locationArea: 'Colombo 07',
        mapCoords: { x: 64, y: 67 },
      },
      {
        id: 'stop-5',
        stopNumber: 5,
        name: 'Waypoint Fresh — Nugegoda',
        status: 'UPCOMING',
        timeText: 'Planned - 11:20',
        locationArea: 'Nugegoda',
        mapCoords: { x: 64, y: 75 },
      },
      {
        id: 'stop-6',
        stopNumber: 6,
        name: 'Final Outlet',
        status: 'UPCOMING',
        timeText: 'Planned - 12:10',
        locationArea: 'Dehiwala',
        mapCoords: { x: 64, y: 82 },
      },
    ],
    constraints: [
      { id: 'c-1', label: 'Weight capacity', value: 'Within limit', status: 'VALID' },
      { id: 'c-2', label: 'Volume capacity', value: 'Within limit', status: 'VALID' },
      { id: 'c-3', label: 'Temperature', value: 'Reefer compatible', status: 'VALID' },
      { id: 'c-4', label: 'Home depot', value: 'Peliyagoda', status: 'VALID' },
      { id: 'c-5', label: 'Fuel quota', value: 'Adequate', status: 'VALID' },
      { id: 'c-6', label: 'Trips per day', value: 'Trip 1 of 2', status: 'VALID' },
      { id: 'c-7', label: 'Delivery window', value: 'Wait & ETA', status: 'WARNING' },
    ],
    activities: [
      { id: 'a-1', time: '07:45', title: 'Loading started', description: 'Loader confirmed trip', status: 'completed' },
      { id: 'a-2', time: '07:50', title: 'Vehicle ready', description: 'Load checklist completed', status: 'completed' },
      { id: 'a-3', time: '08:10', title: 'Trip departed', description: 'Peliyagoda Depot', status: 'completed' },
      { id: 'a-4', time: '09:05', title: 'Delivery completed', description: 'Waypoint Style Wattala', status: 'completed' },
      { id: 'a-5', time: '09:42', title: 'Delivery completed', description: 'Waypoint Tech', status: 'completed' },
      { id: 'a-6', time: '10:10', title: 'Location updated', description: 'Heading to Colombo 07', status: 'current' },
    ],
  },
  {
    id: 'TRIP-0925-018',
    tripCode: 'TRIP-0925-018',
    state: 'IN_TRANSIT',
    monitoringStatus: 'AT_RISK',
    vehicleId: 'VEH021',
    vehicleType: 'Dry Box',
    vehicleFullName: 'Standard Delivery Truck',
    vehiclePlate: 'WP - CAD - 1109',
    driverName: 'Kasun Silva',
    driverInitials: 'KS',
    driverStatus: 'Active · Delayed',
    origin: 'Kandy',
    destination: 'Peradeniya',
    fullRouteText: 'Kandy Depot → Peradeniya District',
    completedStops: 2,
    totalStops: 5,
    eta: '11:35',
    delayText: '+18 min delay',
    nextStopName: 'Peradeniya Main',
    nextStopFullName: 'Waypoint Mart — Peradeniya Main',
    nextStopEta: '11:35',
    nextStopWindow: '11:00 - 11:30',
    nextStopOrder: 'ORD-0925-019',
    weightKg: 2800,
    maxWeightKg: 3500,
    volumeM3: 12.0,
    maxVolumeM3: 15.0,
    chilledItemsCount: 0,
    totalOrdersCount: 5,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Kandy',
    tripUsage: 'Trip 1 of 1',
    todayTrips: '1/1',
    tripLoadedTime: '08:30',
    tripDepartedTime: '08:50',
    stops: [
      { id: 's-18-1', stopNumber: 1, name: 'Kandy Depot', status: 'DEPOT', timeText: 'Departed - 08:50' },
      { id: 's-18-2', stopNumber: 2, name: 'Gannoruwa Outlet', status: 'DELIVERED', timeText: 'Delivered 09:40' },
      { id: 's-18-3', stopNumber: 3, name: 'Peradeniya Main', status: 'NEXT', timeText: 'ETA 11:35' },
      { id: 's-18-4', stopNumber: 4, name: 'Hindagala Store', status: 'UPCOMING', timeText: 'Planned - 12:15' },
      { id: 's-18-5', stopNumber: 5, name: 'Gelioya Point', status: 'UPCOMING', timeText: 'Planned - 12:50' },
    ],
    constraints: [
      { id: 'c-18-1', label: 'Weight capacity', value: 'Within limit', status: 'VALID' },
      { id: 'c-18-2', label: 'Delivery window', value: '+18 min risk', status: 'WARNING' },
    ],
    activities: [
      { id: 'act-18-1', time: '08:30', title: 'Loading started', description: 'Kandy Depot', status: 'completed' },
      { id: 'act-18-2', time: '08:50', title: 'Departed', description: 'En route to Gannoruwa', status: 'completed' },
      { id: 'act-18-3', time: '10:20', title: 'Traffic delay detected', description: 'Congestion on A1 road', status: 'current' },
    ],
  },
  {
    id: 'TRIP-0925-022',
    tripCode: 'TRIP-0925-022',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ISSUE',
    vehicleId: 'VEH033',
    vehicleType: 'Van',
    vehicleFullName: 'Compact Cargo Van',
    vehiclePlate: 'WP - CBA - 8821',
    driverName: 'Ruwan Perera',
    driverInitials: 'RP',
    driverStatus: 'Active · On route',
    origin: 'Peliyagoda',
    destination: 'Gampaha',
    fullRouteText: 'Peliyagoda Depot → Gampaha Hub',
    completedStops: 3,
    totalStops: 4,
    eta: '10:55',
    issueText: 'Delivery issue',
    nextStopName: 'Gampaha City',
    nextStopFullName: 'Waypoint Express — Gampaha',
    nextStopEta: '10:55',
    nextStopWindow: '10:15 - 10:45',
    nextStopOrder: 'ORD-0925-030',
    weightKg: 1100,
    maxWeightKg: 1500,
    volumeM3: 6.2,
    maxVolumeM3: 8.0,
    chilledItemsCount: 0,
    totalOrdersCount: 4,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Peliyagoda',
    tripUsage: 'Trip 2 of 2',
    todayTrips: '2/2',
    tripLoadedTime: '08:00',
    tripDepartedTime: '08:20',
    stops: [
      { id: 's-22-1', stopNumber: 1, name: 'Peliyagoda Depot', status: 'DEPOT', timeText: 'Departed - 08:20' },
      { id: 's-22-2', stopNumber: 2, name: 'Kelaniya Branch', status: 'DELIVERED', timeText: 'Delivered 08:55' },
      { id: 's-22-3', stopNumber: 3, name: 'Kiribathgoda Store', status: 'DELIVERED', timeText: 'Delivered 09:30' },
      { id: 's-22-4', stopNumber: 4, name: 'Gampaha City', status: 'NEXT', timeText: 'ETA 10:55' },
    ],
    constraints: [
      { id: 'c-22-1', label: 'Recipient unreachable', value: 'Customer issue', status: 'ERROR' },
    ],
    activities: [
      { id: 'act-22-1', time: '08:20', title: 'Trip departed', description: 'Peliyagoda Depot', status: 'completed' },
      { id: 'act-22-2', time: '09:45', title: 'Customer contact failed', description: 'Driver attempted 2 calls', status: 'current' },
    ],
  },
  {
    id: 'TRIP-0925-025',
    tripCode: 'TRIP-0925-025',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH041',
    vehicleType: 'Dry Box',
    vehicleFullName: 'Standard Delivery Truck',
    vehiclePlate: 'WP - CAC - 3312',
    driverName: 'Sunil Jayawardena',
    driverInitials: 'SJ',
    driverStatus: 'Active · On route',
    origin: 'Colombo',
    destination: 'Wattala',
    fullRouteText: 'Colombo Central → Wattala Outlets',
    completedStops: 5,
    totalStops: 7,
    eta: '11:15',
    nextStopName: 'Wattala Central',
    nextStopFullName: 'Waypoint Style — Wattala Central',
    nextStopEta: '11:15',
    nextStopWindow: '11:00 - 11:30',
    nextStopOrder: 'ORD-0925-044',
    weightKg: 3100,
    maxWeightKg: 4000,
    volumeM3: 14.0,
    maxVolumeM3: 18.0,
    chilledItemsCount: 0,
    totalOrdersCount: 7,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Peliyagoda',
    tripUsage: 'Trip 1 of 2',
    todayTrips: '1/2',
    stops: [
      { id: 's-25-1', stopNumber: 1, name: 'Colombo Central', status: 'DEPOT', timeText: 'Departed 08:00' },
      { id: 's-25-2', stopNumber: 2, name: 'Fort Outlet', status: 'DELIVERED', timeText: 'Delivered 08:35' },
      { id: 's-25-3', stopNumber: 3, name: 'Pettah Hub', status: 'DELIVERED', timeText: 'Delivered 09:10' },
      { id: 's-25-4', stopNumber: 4, name: 'Kotahena Store', status: 'DELIVERED', timeText: 'Delivered 09:50' },
      { id: 's-25-5', stopNumber: 5, name: 'Peliyagoda North', status: 'DELIVERED', timeText: 'Delivered 10:25' },
      { id: 's-25-6', stopNumber: 6, name: 'Wattala Central', status: 'NEXT', timeText: 'ETA 11:15' },
      { id: 's-25-7', stopNumber: 7, name: 'Mabola Outlet', status: 'UPCOMING', timeText: 'Planned 11:45' },
    ],
    constraints: [],
    activities: [],
  },
  {
    id: 'TRIP-0925-029',
    tripCode: 'TRIP-0925-029',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH016',
    vehicleType: 'Reefer',
    vehicleFullName: 'Refrigerated Truck',
    vehiclePlate: 'WP - CAD - 5589',
    driverName: 'Ajith Wickramasinghe',
    driverInitials: 'AW',
    driverStatus: 'Active · On route',
    origin: 'Peliyagoda',
    destination: 'Negombo',
    fullRouteText: 'Peliyagoda Depot → Negombo Coast',
    completedStops: 3,
    totalStops: 5,
    eta: '11:40',
    nextStopName: 'Ja-Ela',
    nextStopFullName: 'Waypoint Fresh — Ja-Ela',
    nextStopEta: '11:40',
    nextStopWindow: '11:30 - 12:00',
    nextStopOrder: 'ORD-0925-051',
    weightKg: 2900,
    maxWeightKg: 4000,
    volumeM3: 13.5,
    maxVolumeM3: 18.0,
    chilledItemsCount: 15,
    totalOrdersCount: 5,
    temperatureStatus: 'Within range',
    homeDepot: 'Peliyagoda',
    tripUsage: 'Trip 1 of 1',
    todayTrips: '1/1',
    stops: [],
    constraints: [],
    activities: [],
  },
  {
    id: 'TRIP-0925-031',
    tripCode: 'TRIP-0925-031',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH028',
    vehicleType: 'Dry Box',
    vehicleFullName: 'Standard Delivery Truck',
    vehiclePlate: 'WP - CBA - 1045',
    driverName: 'Mahesh Bandara',
    driverInitials: 'MB',
    driverStatus: 'Active · On route',
    origin: 'Kandy',
    destination: 'Matale',
    fullRouteText: 'Kandy Depot → Matale North',
    completedStops: 4,
    totalStops: 6,
    eta: '11:50',
    nextStopName: 'Akurana Outlet',
    nextStopFullName: 'Waypoint Mart — Akurana',
    nextStopEta: '11:50',
    nextStopWindow: '11:30 - 12:00',
    nextStopOrder: 'ORD-0925-058',
    weightKg: 2400,
    maxWeightKg: 3500,
    volumeM3: 11.0,
    maxVolumeM3: 15.0,
    chilledItemsCount: 0,
    totalOrdersCount: 6,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Kandy',
    tripUsage: 'Trip 1 of 2',
    todayTrips: '1/2',
    stops: [],
    constraints: [],
    activities: [],
  },
  {
    id: 'TRIP-0925-034',
    tripCode: 'TRIP-0925-034',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH035',
    vehicleType: 'Van',
    vehicleFullName: 'Compact Cargo Van',
    vehiclePlate: 'WP - CAB - 9912',
    driverName: 'Suresh Kumar',
    driverInitials: 'SK',
    driverStatus: 'Active · On route',
    origin: 'Colombo',
    destination: 'Mount Lavinia',
    fullRouteText: 'Colombo Central → Mount Lavinia',
    completedStops: 2,
    totalStops: 4,
    eta: '10:50',
    nextStopName: 'Wellawatte',
    nextStopFullName: 'Waypoint Tech — Wellawatte',
    nextStopEta: '10:50',
    nextStopWindow: '10:30 - 11:00',
    nextStopOrder: 'ORD-0925-063',
    weightKg: 950,
    maxWeightKg: 1500,
    volumeM3: 5.5,
    maxVolumeM3: 8.0,
    chilledItemsCount: 0,
    totalOrdersCount: 4,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Colombo',
    tripUsage: 'Trip 1 of 2',
    todayTrips: '1/2',
    stops: [],
    constraints: [],
    activities: [],
  },
  {
    id: 'TRIP-0925-038',
    tripCode: 'TRIP-0925-038',
    state: 'IN_TRANSIT',
    monitoringStatus: 'ON_TIME',
    vehicleId: 'VEH044',
    vehicleType: 'Dry Box',
    vehicleFullName: 'Standard Delivery Truck',
    vehiclePlate: 'WP - CAD - 7723',
    driverName: 'Pradeep Kumara',
    driverInitials: 'PK',
    driverStatus: 'Active · On route',
    origin: 'Peliyagoda',
    destination: 'Homagama',
    fullRouteText: 'Peliyagoda Depot → Homagama Industrial',
    completedStops: 1,
    totalStops: 4,
    eta: '11:30',
    nextStopName: 'Maharagama',
    nextStopFullName: 'Waypoint Style — Maharagama',
    nextStopEta: '11:30',
    nextStopWindow: '11:15 - 11:45',
    nextStopOrder: 'ORD-0925-072',
    weightKg: 2100,
    maxWeightKg: 3500,
    volumeM3: 9.8,
    maxVolumeM3: 15.0,
    chilledItemsCount: 0,
    totalOrdersCount: 4,
    temperatureStatus: 'Ambient OK',
    homeDepot: 'Peliyagoda',
    tripUsage: 'Trip 1 of 2',
    todayTrips: '1/2',
    stops: [],
    constraints: [],
    activities: [],
  },
];

*/
export async function fetchLiveTrackingData(): Promise<{ trips: ActiveTrip[]; summary: LiveTrackingSummary }> {
  interface ApiStop { id:string;sequence:number;orderId:string;name:string;district:string;lat?:number;lng?:number;plannedArrival?:string;windowOpen?:string;windowClose?:string;status:string;temperature?:string; }
  interface ApiTrip { tripId:string;tripCode:string;status:string;vehicleId:string;tripNumber:number;homeDepot:string;destination:string;weightKg:number;volumeM3:number;readyAt?:string;departedAt?:string;completedAt?:string;registration:string;vehicleType:string;tempCapability:string;maxWeightKg:number;maxVolumeM3:number;driverName?:string;stops:ApiStop[]; }
  const now=new Date();
  const dates=Array.from({length:7},(_,offset)=>{const d=new Date(now);d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
  const responses=await Promise.all(dates.map(day=>apiRequest<ApiTrip[]>(`/planning/tracking?date=${day}`)));
  const rows=Array.from(new Map(responses.flat().map(row=>[row.tripId,row])).values());
  const trips:ActiveTrip[]=rows.map(row=>{
    const completed=row.stops.filter(s=>/delivered|success|not_delivered|partial/i.test(s.status)).length;
    const next=row.stops.find(s=>!/delivered|success|not_delivered|partial/i.test(s.status))||row.stops[row.stops.length-1];
    const state:ActiveTrip['state']=row.status==='COMPLETED'?'COMPLETED':row.status==='READY_FOR_LOADING'?'READY':/IN_PROGRESS|LOADING/.test(row.status)?'IN_TRANSIT':'PLANNED';
    const type=/van/i.test(row.vehicleType)?'Van':/ambient/i.test(row.tempCapability)?'Dry Box':'Reefer';
    const stops=row.stops.map((s,i)=>({id:s.id,stopNumber:s.sequence,name:s.name,orderId:s.orderId,status:(/not_delivered/i.test(s.status)?'NOT_DELIVERED':/delivered|success/i.test(s.status)?'DELIVERED':/arrived|waiting/i.test(s.status)?'ARRIVED':i===completed?'NEXT':'UPCOMING') as import('@/entities/tracking/trackingTypes').StopStatus,timeText:/arrived/i.test(s.status)?'Driver arrived':/not_delivered/i.test(s.status)?"Can't deliver":s.plannedArrival||'Pending',deliveryWindow:s.windowOpen&&s.windowClose?`${s.windowOpen} - ${s.windowClose}`:'Not specified',locationArea:s.district,lat:s.lat,lng:s.lng}));
    const driverName=row.driverName||'Unassigned';
    return {id:row.tripId,tripCode:row.tripCode,state,monitoringStatus:row.stops.some(s=>/not_delivered/i.test(s.status))?'ISSUE':'ON_TIME',vehicleId:row.vehicleId,vehicleType:type,vehicleFullName:type==='Reefer'?'Refrigerated Truck':type==='Van'?'Cargo Van':'Standard Delivery Truck',vehiclePlate:row.registration||'',driverName,driverInitials:driverName.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase(),driverStatus:state==='IN_TRANSIT'?'Active · On route':state==='READY'?'Ready to depart':'Assigned',origin:row.homeDepot||'',destination:row.destination||next?.district||'',fullRouteText:`${row.homeDepot||'Depot'} → ${row.destination||next?.district||'Route'}`,completedStops:completed,totalStops:row.stops.length,eta:next?.plannedArrival||'—',nextStopName:next?.name||'No stops assigned',nextStopFullName:next?.name||'No stops assigned',nextStopEta:next?.plannedArrival||'—',nextStopWindow:next?.windowOpen&&next?.windowClose?`${next.windowOpen} - ${next.windowClose}`:'Not specified',nextStopOrder:next?.orderId||'',nextStopTemperature:next?.temperature,nextStopItemsText:'Order details',weightKg:row.weightKg,maxWeightKg:row.maxWeightKg,volumeM3:row.volumeM3,maxVolumeM3:row.maxVolumeM3,chilledItemsCount:row.stops.filter(s=>/chill/i.test(s.temperature||'')).length,totalOrdersCount:row.stops.length,temperatureStatus:'Within range',homeDepot:row.homeDepot||'',tripUsage:`Trip ${row.tripNumber||1} of 2`,todayTrips:`${row.tripNumber||1}/2`,tripLoadedTime:row.readyAt?new Date(row.readyAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):undefined,tripDepartedTime:row.departedAt?new Date(row.departedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):undefined,stops,constraints:[],activities:[]};
  });
  return {trips,summary:{activeTripsCount:trips.filter(t=>t.state==='IN_TRANSIT'||t.state==='READY').length,onTimeCount:trips.filter(t=>t.monitoringStatus==='ON_TIME').length,atRiskCount:trips.filter(t=>t.monitoringStatus==='AT_RISK').length,issuesCount:trips.filter(t=>t.monitoringStatus==='ISSUE').length,lastUpdated:new Date().toLocaleTimeString()}};
}

export async function fetchTripDetail(tripId: string): Promise<ActiveTrip | null> {
  const data=await fetchLiveTrackingData();
  return data.trips.find(t=>t.id===tripId||t.tripCode===tripId)||null;
}
