import type { QueueOrder } from '@/entities/order/orderTypes';
import type {
  AffectedOrder, CapacityShortfallData, DeferOrderRequest, DeferredOrder,
  DeferredOrdersSummary, DraftTrip, PlanningSummary, ReturnToRoutePlanningRequest,
  TripValidationResult, UpdateNextPlannedDateRequest, VehicleCandidate,
} from '@/entities/planning/planningTypes';
import { fetchFleetData } from '@/features/fleet/fleetApi';

type CheckStatus = 'PASSED' | 'FAILED' | 'NOT_EVALUATED';
interface ApiErrorBody { message?: string; details?: string[] | Record<string, string>; }
interface ApiOrder { orderId: string; outletId: string; outletName: string; district?: string; depot?: string; parkingType?: string; weightKg: number; volumeM3: number; brand?: string; tempRequirement?: string; preferredDate?: string; windowOpen?: string; windowClose?: string; orderStatus?: string; }
interface ApiCheck { code: string; status: CheckStatus; message: string; blocking: boolean; actualValue?: number; limitValue?: number; }
interface ApiValidation { feasible: boolean; totalWeightKg: number; totalVolumeM3: number; checks: ApiCheck[]; blockingReasons: string[]; }
interface ApiTrip { tripId: string; tripCode?: string; status: string; planningDate: string; homeDepot: string; vehicleId?: string; driverId?: string; totalWeight?: number; totalVolume?: number; orders: Array<Pick<ApiOrder,'orderId'|'outletId'|'outletName'|'weightKg'|'volumeM3'> & { temperatureRequirement?: string }>; stops: Array<{ sequence: number; orderId: string; outletId: string; outletName: string; plannedArrival?: string; windowOpen?: string; windowClose?: string; weightKg: number; volumeM3: number }>; validation?: ApiValidation; }
interface ApiDashboard { totalOrders:number; plannedOrders:number; unplannedOrders:number; deferredOrders:number; availableVehicles:number; totalVehicles:number; availableReefers:number; totalReefers:number; }
interface ApiDeferral { deferralId:string; orderId:string; deliveryDate:string; reason:string; constraintType?:string; retryDate?:string; notified:boolean; createdAt:string; }

export class PlanningApiError extends Error {
  constructor(public status: number, message: string, public details?: ApiErrorBody['details']) { super(message); }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let response: Response;
  try {
    response = await fetch(`/api/planning${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } });
  } catch { throw new PlanningApiError(0, 'Planning Service is unreachable. Check your connection and try again.'); }
  if (!response.ok) {
    let body: ApiErrorBody = {};
    try { body = await response.json() as ApiErrorBody; } catch { /* non-JSON gateway error */ }
    const defaults: Record<number,string> = {400:'The request is invalid.',404:'The requested planning record was not found.',409:'The planning record changed or conflicts with another action.',422:'The plan violates an operational constraint.',500:'Planning Service encountered an error.'};
    throw new PlanningApiError(response.status, body.message || defaults[response.status] || `Planning request failed (${response.status}).`, body.details);
  }
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}

const today = () => new Date().toISOString().slice(0,10);
const depotFor = (o: QueueOrder) => o.routeArea.toLowerCase().startsWith('kandy') ? 'Kandy' : 'Peliyagoda';
const requirement = (v?: string) => /frozen/i.test(v || '') ? 'Frozen' as const : /chill|cold/i.test(v || '') ? 'Chilled' as const : 'Ambient' as const;
const brand = (v?: string) => /style/i.test(v || '') ? 'Style' as const : /tech/i.test(v || '') ? 'Tech' as const : 'Fresh' as const;
function toOrder(o: ApiOrder): QueueOrder { const constraint: QueueOrder['constraint'] = /van/i.test(o.parkingType || '') ? 'Van Only' : requirement(o.tempRequirement)==='Ambient' ? 'Valid' : 'Reefer Required'; return { id:o.orderId, receivedAt:'', isNew:false, outletName:o.outletName, routeArea:`${o.depot || 'Peliyagoda'} - ${o.district || ''}`, brand:brand(o.brand), deliveryWindow:o.windowOpen && o.windowClose ? `${o.windowOpen} - ${o.windowClose}` : 'Not specified', timeSensitive:false, temperature:requirement(o.tempRequirement), weightKg:o.weightKg, volumeM3:o.volumeM3, status:o.orderStatus === 'DEFERRED' ? 'Deferred' : o.orderStatus === 'PLANNED' ? 'Planned' : 'Unplanned', constraint }; }

export async function fetchPlanningOrders(date = today()): Promise<QueueOrder[]> { return (await request<ApiOrder[]>(`/orders/unplanned?date=${date}`)).map(toOrder); }
export async function fetchPlanningSummary(date = today()): Promise<PlanningSummary> { const d=await request<ApiDashboard>(`/dashboard?date=${date}`); return {unplanned:d.unplannedOrders,planned:d.plannedOrders,availableVehicles:d.availableVehicles,totalVehicles:d.totalVehicles,reeferAvailable:d.availableReefers,totalReefer:d.totalReefers,deferred:d.deferredOrders}; }
export async function fetchAvailableVehicles(): Promise<VehicleCandidate[]> { const f=await fetchFleetData(); return f.vehicles.map(v=>({id:v.id,type:v.type==='Dry Box'?'Dry-box Truck':v.type==='Van'?'Small Van':'Reefer',name:`${v.id} - ${v.type}`,weightCapacityKg:v.weightCapacityKg,volumeCapacityM3:v.volumeCapacityM3,driverName:v.driverName,status:v.status,currentDepot:v.depot,isRefrigerated:v.isRefrigerated,tripsToday:v.tripsToday,fuelStatus:v.fuelPercent>=30?'Within quota':'Exceeded'})); }
export function getVehicleEligibilityReason(): string | null { return null; }

function validation(v: ApiValidation|undefined, vehicle: VehicleCandidate|null): TripValidationResult|null { if(!v)return null; const wc=v.checks.find(c=>/WEIGHT/.test(c.code))?.limitValue || vehicle?.weightCapacityKg || 0; const vc=v.checks.find(c=>/VOLUME/.test(c.code))?.limitValue || vehicle?.volumeCapacityM3 || 0; return {feasible:v.feasible,weightUsageKg:v.totalWeightKg,weightCapacityKg:wc,weightPercent:wc?Math.round(v.totalWeightKg/wc*100):0,volumeUsageM3:v.totalVolumeM3,volumeCapacityM3:vc,volumePercent:vc?Math.round(v.totalVolumeM3/vc*100):0,checks:v.checks.map(c=>({id:c.code,name:c.code.split('_').join(' '),passed:c.status==='PASSED',status:c.status,message:c.message})),conflictMessage:v.blockingReasons.join(' ')||undefined}; }
function trip(t: ApiTrip, knownOrders: QueueOrder[]=[], vehicle: VehicleCandidate|null=null): DraftTrip { const byId=new Map(knownOrders.map(o=>[o.id,o])); const apiOrders=new Map(t.orders.map(o=>[o.orderId,o])); const mappedVehicle: VehicleCandidate|null=t.vehicleId ? (vehicle?.id===t.vehicleId?vehicle:{id:t.vehicleId,type:'Assigned vehicle',name:t.vehicleId,weightCapacityKg:0,volumeCapacityM3:0,driverName:t.driverId||'Assigned',status:'Available',currentDepot:t.homeDepot,isRefrigerated:false,tripsToday:0,fuelStatus:'Within quota'}) : null; return {id:t.tripId,status:t.status==='DRAFT'?'DRAFT':'PLANNED',depot:t.homeDepot,vehicle:mappedVehicle,stops:t.stops.map(s=>({id:`${t.tripId}-${s.orderId}`,sequence:s.sequence,order:byId.get(s.orderId)||toOrder({...apiOrders.get(s.orderId)!,orderId:s.orderId,outletId:s.outletId,outletName:s.outletName,weightKg:s.weightKg,volumeM3:s.volumeM3,windowOpen:s.windowOpen,windowClose:s.windowClose,depot:t.homeDepot})})),validation:validation(t.validation,mappedVehicle),distanceKm:0,estDurationMins:0}; }

async function createDraft(orders: QueueOrder[]): Promise<DraftTrip> { if(!orders.length) throw new PlanningApiError(400,'Select at least one order.'); let t=await request<ApiTrip>('/trips',{method:'POST',body:JSON.stringify({planningDate:today(),homeDepot:depotFor(orders[0])})}); for(const o of orders)t=await request<ApiTrip>(`/trips/${t.tripId}/orders`,{method:'POST',body:JSON.stringify({orderId:o.id})}); return trip(t,orders); }
export async function generateSuggestedPlan(orders: QueueOrder[]): Promise<DraftTrip> { const suggestions=await request<{trips:Array<{vehicleId:string;orderIds:string[]}>}>(`/suggestions?date=${today()}`,{method:'POST'}); const selected=orders.length?orders:await fetchPlanningOrders(); const suggestion=suggestions.trips.find(s=>s.orderIds.some(id=>selected.some(o=>o.id===id))); let d=await createDraft(selected.filter(o=>!suggestion||suggestion.orderIds.includes(o.id))); if(suggestion){ const t=await request<ApiTrip>(`/trips/${d.id}/vehicle`,{method:'PUT',body:JSON.stringify({vehicleId:suggestion.vehicleId})}); d=trip(t,selected); } return validateTrip(d); }
export async function addOrderToTrip(d:DraftTrip,o:QueueOrder):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${d.id}/orders`,{method:'POST',body:JSON.stringify({orderId:o.id})}),[...d.stops.map(s=>s.order),o],d.vehicle);}
export async function removeOrderFromTrip(d:DraftTrip,orderId:string):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${d.id}/orders/${orderId}`,{method:'DELETE'}),d.stops.map(s=>s.order),d.vehicle);}
export async function assignTripVehicle(d:DraftTrip,v:VehicleCandidate):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${d.id}/vehicle`,{method:'PUT',body:JSON.stringify({vehicleId:v.id})}),d.stops.map(s=>s.order),v);}
export async function updateTripDepot(d:DraftTrip,depot:string):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${d.id}`,{method:'PUT',body:JSON.stringify({homeDepot:depot})}),d.stops.map(s=>s.order),d.vehicle);}
export async function updateTripStops(d:DraftTrip,ids:string[]):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${d.id}/stops`,{method:'PUT',body:JSON.stringify({orderIds:ids})}),d.stops.map(s=>s.order),d.vehicle);}
export async function validateTrip(d: DraftTrip): Promise<DraftTrip> { return trip(await request<ApiTrip>(`/trips/${d.id}/validate`,{method:'POST'}),d.stops.map(s=>s.order),d.vehicle); }
export async function confirmTrip(d:DraftTrip):Promise<{success:boolean;tripId:string;trip:DraftTrip}>{const t=trip(await request<ApiTrip>(`/trips/${d.id}/confirm`,{method:'POST'}),d.stops.map(s=>s.order),d.vehicle);return {success:true,tripId:t.id,trip:t};}
export async function savePlanningDraft(d:DraftTrip):Promise<DraftTrip>{return request<ApiTrip>(`/trips/${d.id}`).then(t=>trip(t,d.stops.map(s=>s.order),d.vehicle));}
export async function fetchPlannedTrip(id:string):Promise<DraftTrip>{return trip(await request<ApiTrip>(`/trips/${id}`));}

export async function fetchCapacityShortfallData():Promise<CapacityShortfallData>{const s=await request<{totalOrders:number;serviceable:number;requiresDecision:number;affectedOrders:Array<{orderId:string;outletName:string;reason:string;constraintType?:string;retryDate?:string}>}>(`/shortfalls?date=${today()}`);return {constraintType:'ROUTE LIMIT',title:'Capacity Shortfall Detected',subtitle:'Available fleet capacity cannot serve all current delivery demand.',warningTitle:'Planning decisions are required.',warningSubtitle:'Review the affected orders below.',whyExplanation:'These orders could not be allocated by the Planning Service.',summary:{ordersRequiringService:s.totalOrders,canBeServed:s.serviceable,requireDecision:s.requiresDecision,reeferCapacity:0,reeferAvailable:0},affectedOrders:s.affectedOrders.map(a=>({id:a.orderId,outletName:a.outletName,outletShort:a.outletName,depot:'',district:'',brand:'Fresh',requirement:'Ambient',weightKg:0,volumeM3:0,deliveryWindow:'Not specified',timeSensitive:false,risk:'Capacity',decisionState:'Unresolved',recommendation:{action:'DEFER',reason:a.reason}}))};}
export async function recordOrderDeferral(r:DeferOrderRequest){const x=await request<ApiDeferral>(`/orders/${r.orderId}/defer`,{method:'POST',body:JSON.stringify({reason:r.reason,reasonDescription:r.reason,constraintType:'CAPACITY',retryDate:r.nextPlannedDate,nextPlannedDate:r.nextPlannedDate,operationalNote:r.operationalNote})});return {success:true,deferralRecord:{reason:x.reason,nextPlannedDate:x.retryDate||r.nextPlannedDate,operationalNote:r.operationalNote,recordedAt:x.createdAt}};}
export async function recordOrderKeepInPlan(id:string){await request(`/orders/${id}/replan`,{method:'POST'});return {success:true};}
function deferred(d:ApiDeferral):DeferredOrder{return {id:d.orderId,outletName:d.orderId,outletShort:d.orderId,depot:'',depotRegion:'',brand:'Fresh',deferralReasonCategory:/window/i.test(d.constraintType||d.reason)?'Window':/vehicle/i.test(d.constraintType||d.reason)?'Vehicle':/capacity/i.test(d.constraintType||d.reason)?'Capacity':'Other',deferralReasonLabel:d.reason,deferralReasonFull:d.reason,deferralNote:d.reason,deferredAt:new Date(d.createdAt).toLocaleString(),nextPlannedDate:d.retryDate||d.deliveryDate,nextPlannedDateLabel:d.retryDate||d.deliveryDate,queueStatus:d.retryDate?'Scheduled':'Pending',requirement:'Ambient',weightKg:0,volumeM3:0,deliveryWindow:'Not specified',history:[{event:'Deferred by Dispatcher',timestamp:new Date(d.createdAt).toLocaleString()}]};}
export async function fetchDeferredOrders(){const rows=(await request<ApiDeferral[]>(`/deferred?date=${today()}`)).map(deferred);const summary:DeferredOrdersSummary={totalDeferred:rows.length,capacity:rows.filter(x=>x.deferralReasonCategory==='Capacity').length,window:rows.filter(x=>x.deferralReasonCategory==='Window').length,vehicle:rows.filter(x=>x.deferralReasonCategory==='Vehicle').length,other:rows.filter(x=>x.deferralReasonCategory==='Other').length};return {summary,orders:rows};}
export async function getDeferredOrdersSnapshot():Promise<DeferredOrder[]>{return (await fetchDeferredOrders()).orders;}
export async function updateNextPlannedDate(r:UpdateNextPlannedDateRequest){await request(`/deferred/${r.orderId}/next-date`,{method:'PATCH',body:JSON.stringify({nextPlannedDate:r.newDate,reasonForChange:r.reasonForChange})});const refreshed=await fetchDeferredOrders();const updated=refreshed.orders.find(order=>order.id===r.orderId);if(!updated)throw new PlanningApiError(404,'Updated deferred order was not returned by the Planning Service.');return updated;}
export async function returnOrderToPlanning(r:ReturnToRoutePlanningRequest){await request(`/deferred/${r.orderId}/return-to-planning`,{method:'POST'});return {success:true};}
