import React, { useEffect, useState } from 'react';
import { Bell, Camera, ChevronLeft, PenTool } from 'lucide-react';
import { DriverPOD, driverDeliveryApi } from '../driverDeliveryApi';

interface Props { stopId?: string; onBack:()=>void; onConfirmDelivery:()=>void; onOpenNotifications:()=>void; }
export const ProofOfDeliveryView: React.FC<Props> = ({ stopId, onBack, onConfirmDelivery, onOpenNotifications }) => {
  const [pod,setPod]=useState<DriverPOD|null>(null); const [receiver,setReceiver]=useState(''); const [note,setNote]=useState('');
  const [signature,setSignature]=useState<File|null>(null); const [photo,setPhoto]=useState<File|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{ if(!stopId){setError('No delivery stop selected.');return;} driverDeliveryApi.pod(stopId).then(setPod).catch((e:Error)=>setError(e.message)); },[stopId]);
  const confirm=async()=>{ if(!stopId||!pod||!receiver.trim()||!signature||!photo){setError('Receiver name, signature image and delivery photo are required.');return;} setBusy(true);setError('');try{const sig=await driverDeliveryApi.uploadPod(stopId,'signature',signature,receiver.trim());const pic=await driverDeliveryApi.uploadPod(stopId,'photo',photo,receiver.trim());await driverDeliveryApi.confirmPod(stopId,{items:pod.items.map(i=>({item_id:i.item_id,delivered_qty:i.ordered_qty})),receiver_name:receiver.trim(),signature_url:sig.url,photo_url:pic.url,note});onConfirmDelivery();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="driver-screen-content animate-fade-in">
    <div className="driver-header-nav"><button type="button" className="driver-back-btn" onClick={onBack}><ChevronLeft size={22}/></button><h1 className="driver-header-title">Proof of Delivery</h1><button type="button" onClick={onOpenNotifications} style={{marginLeft:'auto',border:0,background:'none'}}><Bell size={21}/></button></div>
    {error&&<div style={{padding:12,borderRadius:12,background:'#fef2f2',color:'#b91c1c',marginBottom:12}}>{error}</div>}
    {!pod&&!error&&<div style={{padding:28,textAlign:'center'}}>Loading delivery details…</div>}
    {pod&&<><section style={{padding:18,borderRadius:20,background:'#fff',border:'1px solid #e2e8f0'}}><strong style={{fontSize:20}}>{pod.outlet.name}</strong><div style={{color:'#64748b'}}>{pod.outlet.id} · Arrived {new Date(pod.arrived_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></section>
    <h3>Items from database</h3><div style={{display:'grid',gap:8}}>{pod.items.map(item=><div key={item.item_id} style={{padding:14,borderRadius:14,background:'#fff',border:'1px solid #e2e8f0',display:'flex',justifyContent:'space-between'}}><strong>{item.name}</strong><span>{item.ordered_qty} units</span></div>)}</div>
    <label style={{display:'block',marginTop:16,fontWeight:700}}>Received by<input value={receiver} onChange={e=>setReceiver(e.target.value)} placeholder="Enter actual receiver name" style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:12,border:'1px solid #cbd5e1',borderRadius:12}}/></label>
    <label style={{display:'block',marginTop:12,fontWeight:700}}>Delivery note<textarea value={note} onChange={e=>setNote(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:12,border:'1px solid #cbd5e1',borderRadius:12}}/></label>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:14}}><label style={{padding:14,borderRadius:14,background:'#fff',border:'1px solid #cbd5e1',fontWeight:700}}><PenTool size={18}/> Signature image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setSignature(e.target.files?.[0]||null)} style={{display:'block',width:'100%',marginTop:8}}/></label><label style={{padding:14,borderRadius:14,background:'#fff',border:'1px solid #cbd5e1',fontWeight:700}}><Camera size={18}/> Delivery photo<input type="file" accept="image/png,image/jpeg,image/webp" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)} style={{display:'block',width:'100%',marginTop:8}}/></label></div>
    <button type="button" disabled={busy} onClick={()=>void confirm()} style={{marginTop:18,width:'100%',padding:15,border:0,borderRadius:14,background:'#facc15',fontWeight:900}}>{busy?'Uploading proof…':'Confirm Delivery'}</button></>}
  </div>;
};
