import React,{useEffect,useState}from'react';
import{AlertTriangle,ChevronLeft,Truck}from'lucide-react';
import{apiRequest}from'@/shared/api/apiClient';
import{DispatcherSidebar}from'@/shared/layouts/DispatcherSidebar';

interface Report{deferralId:string;tripId:string;tripCode:string;stopId:string;orderId:string;outletId:string;outletName:string;reason:string;note:string;driverId:string;driverName:string;vehicleId:string;reportedAt:string;status:string}
export const CantDeliverReviewPage:React.FC<{deferralId:string;onNavigateGlobal?:(page:string)=>void}>=({deferralId,onNavigateGlobal})=>{const[report,setReport]=useState<Report|null>(null),[error,setError]=useState('');useEffect(()=>{apiRequest<Report[]>('/loading/cant-deliver').then(items=>{const found=items.find(x=>x.deferralId===deferralId);if(!found)throw new Error('Can’t-deliver report not found.');setReport(found)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load report.'))},[deferralId]);return <div style={{display:'flex',minHeight:'100vh',background:'#f1f5f9'}}><DispatcherSidebar activePage="route-planning" onNavigate={onNavigateGlobal||(()=>{})}/><main style={{flex:1,padding:'28px 36px'}}><button onClick={()=>onNavigateGlobal?.('dashboard')} style={{border:0,background:'none',color:'#2563eb',display:'flex',gap:5,fontWeight:700}}><ChevronLeft size={16}/>Dashboard</button>{error&&<p style={{color:'#b91c1c'}}>{error}</p>}{report&&<><div style={{display:'flex',justifyContent:'space-between',marginTop:18}}><div><h1 style={{margin:0}}>Can’t Deliver Review</h1><p style={{color:'#64748b'}}>Review the driver’s real delivery exception.</p></div><span style={{background:'#fee2e2',color:'#b91c1c',height:'fit-content',padding:'7px 11px',borderRadius:99,fontWeight:800}}>NOT DELIVERED</span></div><div style={{background:'#fef3c7',border:'1px solid #fbbf24',padding:15,borderRadius:12,display:'flex',gap:10,marginBottom:18}}><AlertTriangle/>Driver reported that {report.outletName} could not receive this delivery.</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:16}}><Card title="Trip"><Info k="Trip" v={report.tripCode}/><Info k="Vehicle" v={report.vehicleId}/><Info k="Driver" v={report.driverName}/></Card><Card title="Delivery stop"><Info k="Outlet" v={report.outletName}/><Info k="Outlet ID" v={report.outletId}/><Info k="Order" v={report.orderId}/></Card><Card title="Driver report"><Info k="Reason" v={report.reason.replaceAll('_',' ')}/><Info k="Reported" v={new Date(report.reportedAt).toLocaleString()}/><Info k="Status" v={report.status}/></Card></div><section style={{background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:20,marginTop:16}}><h2 style={{fontSize:16}}>Driver note</h2><p>{report.note||'No additional note supplied.'}</p><div style={{display:'flex',gap:8,color:'#64748b'}}><Truck size={17}/>This report is stored in deferral_records and included in trip completion.</div></section></>}</main></div>};
const Card:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><section style={{background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:20}}><h2 style={{fontSize:16,marginTop:0}}>{title}</h2>{children}</section>;
const Info=({k,v}:{k:string;v:string})=><div style={{display:'flex',justifyContent:'space-between',gap:10,padding:'9px 0',borderBottom:'1px solid #f1f5f9',fontSize:13}}><span style={{color:'#64748b'}}>{k}</span><strong>{v}</strong></div>;
