package com.waypoint.order;
import com.fasterxml.jackson.databind.JsonNode;import com.waypoint.order.service.OrderOutboxPublisher;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.core.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.client.TestRestTemplate;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;
@EnabledIfEnvironmentVariable(named="ORDER_INTEGRATION",matches="true") @SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"waypoint.outbox.poll-ms=60000"})
class OrderIntegrationTest {
 static final UUID M1=UUID.fromString("22222222-2222-2222-2222-222222222201"),M2=UUID.fromString("22222222-2222-2222-2222-222222222202");
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->System.getenv("TEST_DATABASE_URL"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgrespassword");r.add("spring.rabbitmq.host",()->System.getenv("TEST_RABBITMQ_HOST"));r.add("spring.rabbitmq.port",()->"5672");r.add("spring.rabbitmq.username",()->"guest");r.add("spring.rabbitmq.password",()->"guest");r.add("spring.rabbitmq.virtual-host",()->"/");}
 @Autowired JdbcTemplate jdbc;@Autowired TestRestTemplate http;@Autowired RabbitAdmin admin;@Autowired RabbitTemplate rabbit;@Autowired OrderOutboxPublisher outbox;
 @Test void realPostgresRabbitAndHttpFlow(){
  jdbc.update("UPDATE public.user_profiles SET role='STORE_MANAGER',outlet_id='S1-FRESH-01' WHERE id=?",M1);jdbc.update("UPDATE public.user_profiles SET role='STORE_MANAGER',outlet_id='S1-FRESH-02' WHERE id=?",M2);
  var q=new org.springframework.amqp.core.Queue("order.integration.placed",false,false,false);admin.declareQueue(q);admin.purgeQueue(q.getName(),false);admin.declareBinding(BindingBuilder.bind(q).to(new TopicExchange("waypoint.events",true,false)).with("order.placed"));
  LocalDate date=LocalDate.now(ZoneId.of("Asia/Colombo")).plusDays(2);String body="{\"requestedDeliveryDate\":\""+date+"\",\"items\":[{\"productCode\":\"INT-AMBIENT\",\"quantity\":2,\"weightKg\":1.5,\"volumeM3\":0.2,\"tempRequirement\":\"AMBIENT\",\"unitPrice\":100}]}";
  var h=headers(M1);h.setContentType(MediaType.APPLICATION_JSON);var placed=http.exchange("/api/orders",HttpMethod.POST,new HttpEntity<>(body,h),JsonNode.class);assertThat(placed.getStatusCode()).isEqualTo(HttpStatus.CREATED);UUID id=UUID.fromString(placed.getBody().path("orderId").asText());assertThat(placed.getBody().path("status").asText()).isEqualTo("CONFIRMED");
  var denied=http.exchange("/api/orders/"+id,HttpMethod.GET,new HttpEntity<>(headers(M2)),JsonNode.class);assertThat(denied.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);outbox.publish();awaitMessage();assertThat(jdbc.queryForObject("SELECT count(*) FROM public.order_timeline WHERE order_id=?",Integer.class,id)).isEqualTo(2);
 }
 private void awaitMessage(){for(int i=0;i<20;i++){var m=rabbit.receive("order.integration.placed",500);if(m!=null){assertThat(new String(m.getBody())).contains("INT-AMBIENT");return;}}throw new AssertionError("ORDER_PLACED not received");}
 private HttpHeaders headers(UUID u){var h=new HttpHeaders();h.set("X-Gateway-Verified","true");h.set("X-User-Role","STORE_MANAGER");h.set("X-User-Id",u.toString());return h;}
}
