package com.waypoint.planning.service;

import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.ObjectMapper;
import com.waypoint.planning.constraint.ConstraintEngine;import com.waypoint.planning.dto.DraftTripDtos.*;import com.waypoint.planning.entity.*;import com.waypoint.planning.exception.PlanningException;import com.waypoint.planning.jpa.*;import com.waypoint.planning.messaging.PlanningEventPublisher;import com.waypoint.planning.model.PlanningModels.*;import com.waypoint.planning.port.PlanningMasterDataPort;import com.waypoint.planning.repository.PlanningRepository;
import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class DraftTripService {
 private final TripJpaRepository trips;private final TripStopJpaRepository stops;private final AllocationJpaRepository allocations;private final PlanningDecisionJpaRepository decisions;private final PlanningMasterDataPort master;private final PlanningRepository counts;private final ConstraintEngine constraints;private final PlanningEventPublisher events;private final ObjectMapper json;
 public DraftTripService(TripJpaRepository trips,TripStopJpaRepository stops,AllocationJpaRepository allocations,PlanningDecisionJpaRepository decisions,PlanningMasterDataPort master,PlanningRepository counts,ConstraintEngine constraints,PlanningEventPublisher events,ObjectMapper json){this.trips=trips;this.stops=stops;this.allocations=allocations;this.decisions=decisions;this.master=master;this.counts=counts;this.constraints=constraints;this.events=events;this.json=json;}

 @Transactional public PersistedTripResponse create(CreateTripRequest request){TripEntity trip=trips.save(new TripEntity(request.planningDate(),request.homeDepot()));trip.setTripCode("TRIP-"+request.planningDate().toString().replace("-","")+"-"+trip.getId().toString().substring(0,8).toUpperCase());return view(trips.save(trip),null);}
 @Transactional(readOnly=true) public PersistedTripResponse get(UUID id){return view(find(id),null);}
 @Transactional public PersistedTripResponse update(UUID id,UpdateTripRequest request){TripEntity trip=editable(id);if(request.planningDate()!=null)trip.setPlanningDate(request.planningDate());if(request.homeDepot()!=null&&!request.homeDepot().isBlank())trip.setHomeDepot(request.homeDepot());return view(trip,null);}
 @Transactional public PersistedTripResponse addOrder(UUID id,AddOrderRequest request,String user){TripEntity trip=editable(id);OrderRef order=master.getOrder(request.orderId());if(!"PENDING".equalsIgnoreCase(order.orderStatus()))throw new PlanningException(409,"Order is not planning eligible: "+order.orderStatus());if(allocations.findByTripIdAndOrderId(id,request.orderId()).isPresent())throw new PlanningException(409,"Order is already in this trip");if(allocations.findActiveByOrderId(request.orderId(),List.of(AllocationStatus.TENTATIVE,AllocationStatus.ALLOCATED)).isPresent())throw new PlanningException(409,"Order already has an active planning allocation");try{allocations.save(new AllocationEntity(request.orderId(),id,user));int sequence=stops.findByTripIdOrderBySequence(id).size()+1;stops.save(new TripStopEntity(id,order.orderId(),order.outletId(),sequence,order.windowOpen(),order.windowClose()));}catch(DataIntegrityViolationException ex){throw new PlanningException(409,"Order already has an active planning allocation");}trip.invalidate();recalculate(trip);return view(trip,null);}
 @Transactional public PersistedTripResponse removeOrder(UUID id,UUID orderId){TripEntity trip=editable(id);if(allocations.findByTripIdAndOrderId(id,orderId).isEmpty())throw new PlanningException(404,"Order is not in this trip");allocations.deleteByTripIdAndOrderId(id,orderId);stops.deleteByTripIdAndOrderId(id,orderId);resequence(id);trip.invalidate();recalculate(trip);return view(trip,null);}
 @Transactional public PersistedTripResponse assignVehicle(UUID id,AssignVehicleRequest request){TripEntity trip=editable(id);VehicleRef vehicle=master.getVehicle(request.vehicleId());if(!vehicle.active()||!vehicle.available())throw new PlanningException(409,"Vehicle is not operationally available");trip.setVehicle(vehicle.vehicleId(),vehicle.driverId());allocations.findByTripIdOrderByStopIndex(id).forEach(a->a.assign(vehicle.vehicleId()));return view(trip,null);}
 @Transactional public PersistedTripResponse reorder(UUID id,UpdateStopsRequest request){TripEntity trip=editable(id);List<TripStopEntity> current=stops.findByTripIdOrderBySequence(id);Set<UUID> expected=current.stream().map(TripStopEntity::getOrderId).collect(java.util.stream.Collectors.toSet());if(request.orderIds().size()!=expected.size()||new HashSet<>(request.orderIds()).size()!=request.orderIds().size()||!expected.equals(new HashSet<>(request.orderIds())))throw new PlanningException(400,"Stop order must contain every trip order exactly once");Map<UUID,TripStopEntity> byOrder=new HashMap<>();current.forEach(s->byOrder.put(s.getOrderId(),s));for(int i=0;i<request.orderIds().size();i++)byOrder.get(request.orderIds().get(i)).setSequence(i+1);stops.saveAll(current);trip.invalidate();return view(trip,null);}
 @Transactional public TripValidationResponse validate(UUID id){TripEntity trip=editable(id);ValidationBundle bundle=validateAuthoritatively(trip);trip.setStatus(bundle.result.feasible()?TripStatus.FEASIBLE:TripStatus.INFEASIBLE);trip.setTotals(bundle.result.totalWeightKg(),bundle.result.totalVolumeM3());trip.setValidationSnapshot(snapshot(bundle.result));applyPlannedStops(id,bundle.result);return validationResponse(trip,bundle);}
 @Transactional public PersistedTripResponse confirm(UUID id,String user){TripEntity trip=trips.findByIdForUpdate(id).orElseThrow(()->new PlanningException(404,"Trip not found: "+id));if(trip.getStatus()==TripStatus.CONFIRMED)throw new PlanningException(409,"Trip is already confirmed");if(!trip.editable())throw new PlanningException(409,"Trip cannot be confirmed from status "+trip.getStatus());ValidationBundle bundle=validateAuthoritatively(trip);if(!bundle.result.feasible()){trip.setStatus(TripStatus.INFEASIBLE);throw new PlanningException(422,"Trip is infeasible: "+String.join("; ",bundle.result.blockingReasons()));}int number=counts.tripCount(trip.getVehicleId(),trip.getPlanningDate())+1;if(number>2)throw new PlanningException(409,"Vehicle already has two confirmed trips for this day");trip.setTripNumber(number);trip.setTotals(bundle.result.totalWeightKg(),bundle.result.totalVolumeM3());trip.setValidationSnapshot(snapshot(bundle.result));applyPlannedStops(id,bundle.result);List<AllocationEntity> tripAllocations=allocations.findByTripIdOrderByStopIndex(id);Map<UUID,StopPlan> stopByOrder=new HashMap<>();bundle.result.stops().forEach(s->stopByOrder.put(s.orderId(),s));tripAllocations.forEach(a->{StopPlan s=stopByOrder.get(a.getOrderId());a.assign(trip.getVehicleId());a.position(s.sequence(),s.plannedArrival());a.confirm();});trip.confirm();decisions.save(new PlanningDecisionEntity(null,id,"TRIP_CONFIRMED",trip.getValidationSnapshot()));List<UUID> orderIds=tripAllocations.stream().map(AllocationEntity::getOrderId).toList();events.allocationCompleted(id,trip.getVehicleId(),orderIds,trip.getPlanningDate());return view(trip,bundle.result);}

 private ValidationBundle validateAuthoritatively(TripEntity trip){if(trip.getVehicleId()==null)throw new PlanningException(400,"A vehicle must be assigned before validation");List<UUID> orderIds=allocations.findByTripIdOrderByStopIndex(trip.getId()).stream().map(AllocationEntity::getOrderId).toList();if(orderIds.isEmpty())throw new PlanningException(400,"At least one order is required");List<UUID> sequence=stops.findByTripIdOrderBySequence(trip.getId()).stream().map(TripStopEntity::getOrderId).toList();VehicleRef vehicle=master.getVehicle(trip.getVehicleId());ValidationResult result=constraints.validate(master.getOrders(orderIds),vehicle,trip.getPlanningDate(),sequence);return new ValidationBundle(vehicle,result);}
 private void applyPlannedStops(UUID id,ValidationResult result){Map<UUID,TripStopEntity> persisted=new HashMap<>();stops.findByTripIdOrderBySequence(id).forEach(s->persisted.put(s.getOrderId(),s));result.stops().forEach(s->{TripStopEntity entity=persisted.get(s.orderId());entity.setSequence(s.sequence());entity.setPlannedArrival(s.plannedArrival());});}
 private void recalculate(TripEntity trip){List<OrderRef> orders=master.getOrders(allocations.findByTripIdOrderByStopIndex(trip.getId()).stream().map(AllocationEntity::getOrderId).toList());trip.setTotals(orders.stream().mapToDouble(OrderRef::weightKg).sum(),orders.stream().mapToDouble(OrderRef::volumeM3).sum());}
 private void resequence(UUID id){List<TripStopEntity> list=stops.findByTripIdOrderBySequence(id);for(int i=0;i<list.size();i++)list.get(i).setSequence(i+1);}
 private TripEntity find(UUID id){return trips.findById(id).orElseThrow(()->new PlanningException(404,"Trip not found: "+id));}private TripEntity editable(UUID id){TripEntity t=find(id);if(!t.editable())throw new PlanningException(409,"Trip is immutable in status "+t.getStatus());return t;}
 private PersistedTripResponse view(TripEntity trip,ValidationResult validation){List<OrderRef> orders=master.getOrders(allocations.findByTripIdOrderByStopIndex(trip.getId()).stream().map(AllocationEntity::getOrderId).toList());Map<UUID,OrderRef> byId=new HashMap<>();orders.forEach(o->byId.put(o.orderId(),o));List<DraftOrder> orderViews=orders.stream().map(o->new DraftOrder(o.orderId(),o.outletId(),o.outletName(),o.weightKg(),o.volumeM3(),o.tempRequirement())).toList();List<StopPlan> stopViews=stops.findByTripIdOrderBySequence(trip.getId()).stream().map(s->{OrderRef o=byId.get(s.getOrderId());return new StopPlan(s.getSequence(),s.getOrderId(),s.getOutletId(),o==null?null:o.outletName(),s.getPlannedArrival(),s.getWindowStart(),s.getWindowEnd(),o==null?0:o.weightKg(),o==null?0:o.volumeM3());}).toList();return new PersistedTripResponse(trip.getId(),trip.getTripCode(),trip.getStatus().name(),trip.getPlanningDate(),trip.getHomeDepot(),trip.getVehicleId(),trip.getDriverId(),trip.getTripNumber(),trip.getTotalWeight(),trip.getTotalVolume(),orderViews,stopViews,validation);}
 private TripValidationResponse validationResponse(TripEntity trip,ValidationBundle b){return new TripValidationResponse(trip.getId(),b.result.feasible(),b.result.totalWeightKg(),b.vehicle.weightCapKg(),b.result.totalVolumeM3(),b.vehicle.volumeCapM3(),b.result.checks(),b.result.blockingReasons());}
 private String snapshot(ValidationResult result){try{return json.writeValueAsString(result);}catch(JsonProcessingException ex){throw new PlanningException(500,"Unable to persist validation snapshot");}}
 private record ValidationBundle(VehicleRef vehicle,ValidationResult result){}
}
