package com.waypoint.planning;

import com.waypoint.planning.dto.PlanningModels.*;import com.waypoint.planning.service.*;import org.junit.jupiter.api.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;

class AllocationEngineTest {
  AllocationEngine engine=new AllocationEngine();LocalDate date=LocalDate.of(2026,10,4);
  Map<String,TravelInput> travel=Map.of("D1|Colombo",new TravelInput("D1","Colombo",30,10,20),"D1|Gampaha",new TravelInput("D1","Gampaha",40,15,30));
  Map<String,Integer> allowances=Map.of("Fresh|STANDARD",15,"Fresh|VAN_ONLY",15,"Fresh|MALL",20,"Style|STANDARD",20,"Tech|STANDARD",25);
  OutletInput outlet(String id,String district,String dock){return new OutletInput(id,id,district,"D1","STANDARD",dock,null,null,null);}
  OrderInput order(String id,String brand,String temp,double kg,double vol,OutletInput out){return new OrderInput(UUID.nameUUIDFromBytes(id.getBytes()),out.outletId(),id,10,kg,vol,brand,temp,date,LocalTime.of(6,0),LocalTime.of(17,0),1000,OffsetDateTime.now(),false,1,out);}
  VehicleInput vehicle(String id,String brand,String type,String temp,double kg,double vol){return new VehicleInput(id,id,type,kg,vol,temp,"D1",brand,UUID.nameUUIDFromBytes((id+"d").getBytes()),5,500,0,false);}
  String reason(AllocationResult r){return r.deferred().getFirst().reason();}

  @Test void sameBrandAndDistrictPerTrip(){var v=vehicle("V","ALL","TRUCK","CHILLED",5000,50);var a=order("A","Fresh","AMBIENT",100,1,outlet("A","Colombo","STANDARD"));var b=order("B","Style","AMBIENT",100,1,outlet("B","Colombo","STANDARD"));var c=order("C","Fresh","AMBIENT",100,1,outlet("C","Gampaha","STANDARD"));var r=engine.allocate(date,List.of(a,b,c),List.of(v),travel,allowances);assertThat(r.servedTrips()).allSatisfy(t->{assertThat(t.stops().stream().flatMap(s->s.orders().stream()).map(OrderInput::brand).distinct().count()).isEqualTo(1);assertThat(t.stops().stream().map(StopPlan::district).distinct().count()).isEqualTo(1);});}
  @Test void chilledRequiresReefer(){assertThat(reason(engine.allocate(date,List.of(order("A","Fresh","CHILLED",100,1,outlet("A","Colombo","STANDARD"))),List.of(vehicle("V","Fresh","TRUCK","AMBIENT",1000,10)),travel,allowances))).isEqualTo("REEFER_SHORTAGE");}
  @Test void vanOnlyRequiresVan(){assertThat(reason(engine.allocate(date,List.of(order("A","Fresh","AMBIENT",100,1,outlet("A","Colombo","VAN_ONLY"))),List.of(vehicle("V","Fresh","TRUCK","AMBIENT",1000,10)),travel,allowances))).isEqualTo("VAN_ONLY");}
  @Test void vehicleUsesHomeDepot(){var wrong=new VehicleInput("V","V","TRUCK",1000,10,"AMBIENT","D2","Fresh",UUID.randomUUID(),5,500,0,false);assertThat(engine.allocate(date,List.of(order("A","Fresh","AMBIENT",100,1,outlet("A","Colombo","STANDARD"))),List.of(wrong),travel,allowances).servedTrips()).isEmpty();}
  @Test void wholeOrdersAreNeverSplit(){var o=order("A","Fresh","AMBIENT",900,9,outlet("A","Colombo","STANDARD"));var r=engine.allocate(date,List.of(o),List.of(vehicle("V","Fresh","TRUCK","AMBIENT",1000,10)),travel,allowances);assertThat(r.servedTrips().getFirst().stops().getFirst().orders()).containsExactly(o);}
  @Test void weightAndVolumeCapsBothApply(){var v=vehicle("V","Fresh","TRUCK","AMBIENT",1000,10);assertThat(reason(engine.allocate(date,List.of(order("W","Fresh","AMBIENT",1001,1,outlet("W","Colombo","STANDARD"))),List.of(v),travel,allowances))).isEqualTo("CAPACITY");assertThat(reason(engine.allocate(date,List.of(order("X","Fresh","AMBIENT",100,11,outlet("X","Colombo","STANDARD"))),List.of(v),travel,allowances))).isEqualTo("CAPACITY");}
  @Test void atMostTwoTripsAndFormulaApplied(){var v=vehicle("V","Fresh","TRUCK","AMBIENT",150,10);var orders=List.of(order("A","Fresh","AMBIENT",100,1,outlet("A","Colombo","STANDARD")),order("B","Fresh","AMBIENT",100,1,outlet("B","Colombo","STANDARD")),order("C","Fresh","AMBIENT",100,1,outlet("C","Colombo","STANDARD")));var r=engine.allocate(date,orders,List.of(v),travel,allowances);assertThat(r.servedTrips()).hasSize(2);assertThat(r.deferred()).hasSize(1);assertThat(r.servedTrips().getFirst().tripMinutes()).isEqualTo(45);}
  @Test void styleAndTechShareThe480MinuteVehicleBudget(){var slow=Map.of("D1|Colombo",new TravelInput("D1","Colombo",250,20,10));var orders=List.of(order("S","Style","AMBIENT",100,1,outlet("S","Colombo","STANDARD")),order("T","Tech","AMBIENT",100,1,outlet("T","Colombo","STANDARD")));var r=engine.allocate(date,orders,List.of(vehicle("V","ALL","TRUCK","AMBIENT",1000,10)),slow,Map.of("Style|STANDARD",10,"Tech|STANDARD",10));assertThat(r.servedTrips()).hasSize(1);assertThat(r.deferred()).singleElement().extracting(DeferredOrder::reason).isEqualTo("TIME_BUDGET");}
  @Test void deliveryWindowAndFuelQuotaEnforced(){var late=new OrderInput(UUID.randomUUID(),"A","A",1,10,1,"Fresh","AMBIENT",date,LocalTime.of(6,0),LocalTime.of(6,10),10,OffsetDateTime.now(),false,1,outlet("A","Colombo","STANDARD"));assertThat(reason(engine.allocate(date,List.of(late),List.of(vehicle("V","Fresh","TRUCK","AMBIENT",1000,10)),travel,allowances))).isEqualTo("WINDOW");var fuel=new VehicleInput("F","F","TRUCK",1000,10,"AMBIENT","D1","Fresh",UUID.randomUUID(),1,5,0,false);assertThat(reason(engine.allocate(date,List.of(order("B","Fresh","AMBIENT",10,1,outlet("B","Colombo","STANDARD"))),List.of(fuel),travel,allowances))).isEqualTo("FUEL_QUOTA");}
  @Test void workshopVehiclesSkipped(){var base=vehicle("V","Fresh","TRUCK","AMBIENT",1000,10);var workshop=new VehicleInput(base.vehicleId(),base.registration(),base.type(),base.weightCapKg(),base.volumeCapM3(),base.tempCapability(),base.depot(),base.brand(),base.driverId(),base.kmPerL(),base.weeklyFuelQuotaL(),base.fuelUsedWeekL(),true);assertThat(engine.allocate(date,List.of(order("A","Fresh","AMBIENT",10,1,outlet("A","Colombo","STANDARD"))),List.of(workshop),travel,allowances).servedTrips()).isEmpty();}
  @Test void priorityOrderingAndDeterminism(){var low=order("LOW","Fresh","AMBIENT",10,1,outlet("L","Colombo","STANDARD"));var high=new OrderInput(UUID.nameUUIDFromBytes("HIGH".getBytes()),"H","H",10,10,1,"Fresh","AMBIENT",date,LocalTime.of(6,0),LocalTime.of(17,0),10,OffsetDateTime.now(),true,20,outlet("H","Colombo","STANDARD"));assertThat(engine.priorityComparator().compare(high,low)).isLessThan(0);var fleet=List.of(vehicle("V","Fresh","TRUCK","AMBIENT",1000,10));assertThat(engine.allocate(date,List.of(low,high),fleet,travel,allowances)).isEqualTo(engine.allocate(date,List.of(low,high),fleet,travel,allowances));}
  @Test void s1HasZeroValidatorViolations(){var fleet=List.of(vehicle("RF","Fresh","TRUCK","CHILLED",5000,24),vehicle("SV","Style","VAN","AMBIENT",1500,10),vehicle("TT","Tech","TRUCK","AMBIENT",4000,20));var orders=List.of(order("F1","Fresh","AMBIENT",900,4,outlet("F1","Colombo","STANDARD")),order("F2","Fresh","CHILLED",700,3,outlet("F2","Colombo","STANDARD")),order("S1","Style","AMBIENT",600,2.5,outlet("S1","Gampaha","STANDARD")),order("T1","Tech","AMBIENT",1000,5,outlet("T1","Gampaha","STANDARD")));var r=engine.allocate(date,orders,fleet,travel,allowances);assertThat(new AllocationValidator(engine).checkAllocation(r,fleet,travel,allowances)).isEmpty();}
}
