package com.waypoint.planning.grpc;

import com.waypoint.planning.dto.DraftTripDtos.PersistedTripResponse;import com.waypoint.planning.entity.TripStatus;import com.waypoint.planning.exception.PlanningException;import com.waypoint.planning.jpa.TripJpaRepository;import com.waypoint.planning.model.PlanningModels.*;import com.waypoint.planning.service.*;import io.grpc.Status;import io.grpc.stub.StreamObserver;import net.devh.boot.grpc.server.service.GrpcService;
import java.time.*;import java.util.*;

@GrpcService
public class PlanningGrpcService extends PlanningServiceGrpc.PlanningServiceImplBase {
 private final DraftTripService drafts;private final TripJpaRepository trips;private final DeferralService deferrals;private final SuggestionService suggestions;
 public PlanningGrpcService(DraftTripService drafts,TripJpaRepository trips,DeferralService deferrals,SuggestionService suggestions){this.drafts=drafts;this.trips=trips;this.deferrals=deferrals;this.suggestions=suggestions;}
 @Override public void getTrip(GetTripRequest request,StreamObserver<GetTripResponse> observer){respond(observer,()->{PersistedTripResponse value=drafts.get(uuid(request.getTripId()));if(!confirmed(value.status()))throw new PlanningException(404,"Confirmed trip not found");return GetTripResponse.newBuilder().setTrip(map(value)).build();});}
 @Override public void listTrips(ListTripsRequest request,StreamObserver<ListTripsResponse> observer){respond(observer,()->{LocalDate date=LocalDate.parse(request.getDeliveryDate());var entities=trips.findByPlanningDateAndStatusInOrderByTripCode(date,List.of(TripStatus.CONFIRMED,TripStatus.READY_FOR_LOADING,TripStatus.PLANNED,TripStatus.LOADING,TripStatus.IN_PROGRESS,TripStatus.COMPLETED));var out=ListTripsResponse.newBuilder();for(var entity:entities){PersistedTripResponse value=drafts.get(entity.getId());if((request.getVehicleId().isBlank()||request.getVehicleId().equals(value.vehicleId()))&&(request.getStatus().isBlank()||request.getStatus().equals(value.status())))out.addTrips(map(value));}return out.setTotal(out.getTripsCount()).build();});}
 @Override public void deferOrder(DeferOrderRequest request,StreamObserver<DeferOrderResponse> observer){respond(observer,()->{UUID id=uuid(request.getOrderId());LocalDate next=request.getRetryDate().isBlank()?null:LocalDate.parse(request.getRetryDate());deferrals.defer(id,new DeferralRequest(request.getReason(),request.getConstraintType(),request.getReason(),request.getConstraintType(),next,next,null),"GRPC");return DeferOrderResponse.newBuilder().setOrderId(id.toString()).setStatus("DEFERRED").setRetryDate(next==null?"":next.toString()).setMessage("Order deferred").build();});}
 @Override public void allocateOrders(AllocateOrdersRequest request,StreamObserver<AllocateOrdersResponse> observer){observer.onError(Status.FAILED_PRECONDITION.withDescription("Automatic confirmation is disabled. Use POST /api/planning/suggestions and Dispatcher confirmation.").asRuntimeException());}
 private Trip map(PersistedTripResponse value){Trip.Builder out=Trip.newBuilder().setTripId(value.tripId().toString()).setVehicleId(nvl(value.vehicleId())).setDriverId(value.driverId()==null?"":value.driverId().toString()).setTripNumber(value.tripNumber()==null?0:value.tripNumber()).setDeliveryDate(value.planningDate().toString()).setStatus(value.status()).setTotalWeightKg(value.totalWeight()).setTotalVolumeM3(value.totalVolume()).setHomeDepot(nvl(value.homeDepot()));for(StopPlan s:value.stops()){out.addStopSequence(s.outletId());out.addOrders(TripOrder.newBuilder().setOrderId(s.orderId().toString()).setOutletId(s.outletId()).setStopIndex(s.sequence()).setPlannedArrival(s.plannedArrival()==null?"":s.plannedArrival().toString()).setDeliveryWindowStart(s.windowOpen()==null?"":s.windowOpen().toString()).setDeliveryWindowEnd(s.windowClose()==null?"":s.windowClose().toString()));}return out.build();}
 private static boolean confirmed(String s){return Set.of("CONFIRMED","READY_FOR_LOADING","PLANNED","LOADING","IN_PROGRESS","COMPLETED").contains(s);}private static UUID uuid(String v){try{return UUID.fromString(v);}catch(Exception ex){throw new PlanningException(400,"Invalid UUID: "+v);}}private static String nvl(String v){return v==null?"":v;}
 private <T> void respond(StreamObserver<T> observer,java.util.function.Supplier<T> work){try{observer.onNext(work.get());observer.onCompleted();}catch(PlanningException ex){Status status=ex.status()==404?Status.NOT_FOUND:ex.status()==409?Status.ALREADY_EXISTS:ex.status()==400?Status.INVALID_ARGUMENT:Status.INTERNAL;observer.onError(status.withDescription(ex.getMessage()).asRuntimeException());}catch(Exception ex){observer.onError(Status.INTERNAL.withDescription("Planning operation failed").asRuntimeException());}}
}
