package com.waypoint.planning.constraint;

import com.fasterxml.jackson.databind.ObjectMapper;import com.waypoint.planning.dto.DraftTripDtos.*;import com.waypoint.planning.entity.*;import com.waypoint.planning.exception.PlanningException;import com.waypoint.planning.jpa.*;import com.waypoint.planning.messaging.PlanningEventPublisher;import com.waypoint.planning.model.PlanningModels.*;import com.waypoint.planning.port.PlanningMasterDataPort;import com.waypoint.planning.repository.PlanningRepository;import com.waypoint.planning.service.DraftTripService;import org.junit.jupiter.api.*;import org.springframework.test.util.ReflectionTestUtils;
import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class DraftTripServiceTest {
 private TripJpaRepository trips;private TripStopJpaRepository stops;private AllocationJpaRepository allocations;private PlanningDecisionJpaRepository decisions;private PlanningMasterDataPort master;private PlanningRepository counts;private PlanningEventPublisher events;private DraftTripService service;private TripEntity trip;private OrderRef order;private VehicleRef vehicle;private UUID tripId;
 @BeforeEach void setup(){trips=mock(TripJpaRepository.class);stops=mock(TripStopJpaRepository.class);allocations=mock(AllocationJpaRepository.class);decisions=mock(PlanningDecisionJpaRepository.class);master=mock(PlanningMasterDataPort.class);counts=mock(PlanningRepository.class);events=mock(PlanningEventPublisher.class);var validators=List.<ConstraintValidator>of(new WeightConstraintValidator(),new VolumeConstraintValidator(),new TemperatureConstraintValidator(),new OutletAccessConstraintValidator(),new HomeDepotConstraintValidator(),new DeliveryWindowConstraintValidator(),new FuelQuotaConstraintValidator(),new TripsPerDayConstraintValidator(),new VehicleAvailabilityConstraintValidator(),new BrandConstraintValidator(),new DistrictConstraintValidator(),new DuplicateAllocationConstraintValidator());service=new DraftTripService(trips,stops,allocations,decisions,master,counts,new ConstraintEngine(counts,validators),events,new ObjectMapper().findAndRegisterModules());tripId=UUID.randomUUID();trip=new TripEntity(LocalDate.of(2026,9,25),"D1");ReflectionTestUtils.setField(trip,"id",tripId);order=new OrderRef(UUID.randomUUID(),"OUT","Outlet","Colombo","D1","STANDARD",null,null,"SKU",1,820,7.8,"Fresh","CHILLED",trip.getPlanningDate(),LocalTime.of(6,0),LocalTime.of(12,0),"CONFIRMED");vehicle=new VehicleRef("VEH","REG","TRUCK",4000,18,"CHILLED","D1","Fresh",UUID.randomUUID(),true,true,100,50);when(trips.findById(tripId)).thenReturn(Optional.of(trip));when(trips.findByIdForUpdate(tripId)).thenReturn(Optional.of(trip));when(master.getOrder(order.orderId())).thenReturn(order);when(master.getVehicle(vehicle.vehicleId())).thenReturn(vehicle);when(master.getOrders(anyCollection())).thenAnswer(i->{Collection<UUID> ids=i.getArgument(0);return ids.contains(order.orderId())?List.of(order):List.of();});}
 @Test void createsPersistedDraft(){when(trips.save(any())).thenAnswer(i->{TripEntity t=i.getArgument(0);if(t.getId()==null)ReflectionTestUtils.setField(t,"id",tripId);return t;});var result=service.create(new CreateTripRequest(trip.getPlanningDate(),"D1"));assertThat(result.status()).isEqualTo("DRAFT");assertThat(result.tripCode()).startsWith("TRIP-20260925-");}
 @Test void addsAndRemovesOrder(){AllocationEntity allocation=new AllocationEntity(order.orderId(),tripId,"user");when(stops.findByTripIdOrderBySequence(tripId)).thenReturn(List.of());when(allocations.findByTripIdOrderByStopIndex(tripId)).thenReturn(List.of(allocation));var added=service.addOrder(tripId,new AddOrderRequest(order.orderId()),"user");assertThat(added.totalWeight()).isEqualTo(820);verify(allocations).save(any(AllocationEntity.class));verify(stops).save(any(TripStopEntity.class));when(allocations.findByTripIdAndOrderId(tripId,order.orderId())).thenReturn(Optional.of(allocation));when(allocations.findByTripIdOrderByStopIndex(tripId)).thenReturn(List.of());service.removeOrder(tripId,order.orderId());verify(allocations).deleteByTripIdAndOrderId(tripId,order.orderId());verify(stops).deleteByTripIdAndOrderId(tripId,order.orderId());}
 @Test void assignsVehicleAndInvalidatesValidation(){trip.setStatus(TripStatus.FEASIBLE);service.assignVehicle(tripId,new AssignVehicleRequest(vehicle.vehicleId()));assertThat(trip.getStatus()).isEqualTo(TripStatus.DRAFT);assertThat(trip.getVehicleId()).isEqualTo("VEH");}
 @Test void reordersOnlyExactOrderSet(){TripStopEntity stop=new TripStopEntity(tripId,order.orderId(),order.outletId(),1,order.windowOpen(),order.windowClose());when(stops.findByTripIdOrderBySequence(tripId)).thenReturn(List.of(stop));service.reorder(tripId,new UpdateStopsRequest(List.of(order.orderId())));assertThatThrownBy(()->service.reorder(tripId,new UpdateStopsRequest(List.of(UUID.randomUUID())))).isInstanceOf(PlanningException.class);}
 @Test void validatesAndConfirmsPersistedDraft(){prepareAssignedDraft();var validation=service.validate(tripId);assertThat(validation.feasible()).isTrue();trip.setStatus(TripStatus.FEASIBLE);var confirmed=service.confirm(tripId,"dispatcher");assertThat(confirmed.status()).isEqualTo("CONFIRMED");verify(events).allocationCompleted(eq(tripId),eq("VEH"),eq(vehicle.driverId()),eq(1),eq(trip.getPlanningDate()),eq("dispatcher"),eq(List.of(order)),any(ValidationResult.class));}
 @Test void duplicateConfirmationIsIdempotentWithoutEvent(){trip.confirm();assertThat(service.confirm(tripId,"dispatcher").status()).isEqualTo("CONFIRMED");verifyNoInteractions(events);}
 @Test void rejectsInfeasibleConfirmationWithoutEvent(){vehicle=new VehicleRef("VEH","REG","TRUCK",4000,18,"AMBIENT","D1","Fresh",null,true,true,100,50);prepareAssignedDraft();assertThatThrownBy(()->service.confirm(tripId,"dispatcher")).isInstanceOf(PlanningException.class).hasMessageContaining("infeasible");verifyNoInteractions(events);}
 private void prepareAssignedDraft(){trip.setVehicle(vehicle.vehicleId(),vehicle.driverId());AllocationEntity allocation=new AllocationEntity(order.orderId(),tripId,"user");TripStopEntity stop=new TripStopEntity(tripId,order.orderId(),order.outletId(),1,order.windowOpen(),order.windowClose());when(allocations.findByTripIdOrderByStopIndex(tripId)).thenReturn(List.of(allocation));when(stops.findByTripIdOrderBySequence(tripId)).thenReturn(List.of(stop));when(master.getVehicle(vehicle.vehicleId())).thenReturn(vehicle);when(counts.tripCount(vehicle.vehicleId(),trip.getPlanningDate())).thenReturn(0);}
}
