ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'VALIDATING';
ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'FEASIBLE';
ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'INFEASIBLE';
ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE public.trip_status ADD VALUE IF NOT EXISTS 'READY_FOR_LOADING';
ALTER TYPE public.allocation_status ADD VALUE IF NOT EXISTS 'TENTATIVE';
