import React,{useEffect,useState}from'react';import{Clock,Edit3,User,Warehouse,Info}from'lucide-react';import{loadingApi}from'../api';import type{ApiProblem,TripDetail}from'../types';import{EditRouteModal}from'./EditRouteModal';import{TruckIllustration}from'./TruckIllustration';
interface Props{tripId:string|null;onLoadItemClick?:(stopId:string)=>void}
export const TripDetailView:React.FC<Props>=({tripId,onLoadItemClick})=>{const[data,setData]=useState<TripDetail|null>(null),[error,setError]=useState<ApiProblem|null>(null),[busy,setBusy]=useState(true),[modal,setModal]=useState(false);
const load=()=>{if(!tripId)return;setBusy(true);loadingApi.trip(tripId).then(x=>{setData({...x,stops:x.stops??[]});setError(null)}).catch(setError).finally(()=>setBusy(false))};useEffect(load,[tripId]);
const act=async(stopId:string,next:string)=>{if(!tripId)return;try{if(next==='START_LOADING')await loadingApi.start(tripId,stopId);onLoadItemClick?.(stopId)}catch(e){setError(e as ApiProblem)}};
if(!tripId)return <div className="loading-state">Select a trip to view its loading plan.</div>;if(busy)return <div className="loading-state" role="status">Loading trip detail…</div>;if(error||!data)return <div className="loading-state" role="alert">{error?.status===409?'Plan acknowledgement required before loading can continue.':error?.status===422?error.message:`Unable to load trip: ${error?.message||'Unknown error'}`}</div>;
return <div className="trip-detail-page" style={{width:'100%'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:20}}><div><h1 style={{fontSize:26,fontWeight:700,color:'#0F172A',margin:0}}>Trip Detail</h1><p style={{fontSize:13.5,color:'#64748B',marginTop:4}}>{data.header.tripCode} · {data.header.origin} → {data.header.destination}</p></div><button type="button" onClick={()=>setModal(true)} style={{display:'flex',gap:8,padding:'9px 14px',border:'1px solid #CBD5E1',borderRadius:8,background:'#fff'}}><Edit3 size={16}/> Edit route</button></div>
{data.planBanner&&<div style={{background:'#FFFBEB',border:'1px solid #FDE68A',borderRadius:12,padding:16,marginBottom:18,display:'flex',gap:10}}><Info size={18}/><div><strong>Plan updated</strong><div style={{fontSize:13,color:'#64748B'}}>Review the latest route changes before continuing.</div></div></div>}
<div className="trip-summary-grid" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14,marginBottom:20}}><section style={card}><TruckIllustration/><strong>{data.vehicle.vehicleId}</strong><span>{data.vehicle.loadedKg.toLocaleString()} / {data.vehicle.capacityKg.toLocaleString()} kg</span></section><section style={card}><User size={18}/><strong>{data.driver.name}</strong><span>{data.header.status}</span></section><section style={card}><Warehouse size={18}/><strong>{data.dock}</strong><span>{data.shift}</span></section><section style={card}><Clock size={18}/><strong>{data.plannedStart}</strong><span>{data.totals.itemsChecked}/{data.totals.itemsTotal} items checked</span></section></div>
<div style={{display:'grid',gap:12}}>{data.stops.map(s=><article key={s.stopId} style={{...card,display:'grid',gridTemplateColumns:'44px 1fr auto',alignItems:'center',gap:14}}><div style={{width:34,height:34,borderRadius:'50%',display:'grid',placeItems:'center',background:s.status==='LOADED'?'#DCFCE7':'#FEF3C7',fontWeight:700}}>{s.loadOrder}</div><div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong>{s.outlet}</strong>{s.changeFlag&&<span style={{fontSize:11,color:'#B45309',background:'#FEF3C7',padding:'2px 7px',borderRadius:12}}>{s.changeFlag}</span>}</div><p style={{fontSize:13,color:'#64748B',margin:'4px 0'}}>{s.area} · {s.dockNote} · {s.itemsRemaining} items remaining</p><span style={{fontSize:12,color:'#475569'}}>{s.crates||s.units} {s.crates?'crates':'units'} · {s.weightKg.toLocaleString()} kg</span></div><button disabled={s.nextAction==='DONE'} onClick={()=>act(s.stopId,s.nextAction)} style={{padding:'9px 13px',borderRadius:8,background:s.nextAction==='LOAD_NEXT'?'#F5A623':'#fff',border:'1px solid #CBD5E1',fontWeight:600}}>{s.nextAction==='DONE'?'Loaded':s.nextAction.replaceAll('_',' ').toLowerCase()}</button></article>)}</div>
<EditRouteModal isOpen={modal} onClose={()=>setModal(false)} tripId={tripId} stops={data.stops} onSaved={()=>{setModal(false);load()}}/></div>};
const card:React.CSSProperties={background:'#fff',border:'1px solid #E2E8F0',borderRadius:12,padding:16,display:'flex',flexDirection:'column',gap:6};
